// generated by Fast Light User Interface Designer (fluid) version 1.0404

#include "fskioUI.h"
#include "gettext.h"
#ifndef gettext_noop
#  define gettext_noop(text) text
#endif
#include "config.h"
#include "compat.h"
#include "fsk.h"
#include "fsklog.h"
Fl_Text_Buffer *FSK_sent_buffer;
Fl_Double_Window *fsklog_viewer;

FTextView *FSK_sent_text=(FTextView *)0;

FTextEdit *FSK_txt_to_send=(FTextEdit *)0;

static void cb_FSK_txt_to_send(FTextEdit*, void*) {
  FSK_control_function_keys();
}

Fl_Button *btn_fskio_config=(Fl_Button *)0;

static void cb_btn_fskio_config(Fl_Button*, void*) {
  FSK_open_config();
}

Fl_Button *btn_fskio_clear=(Fl_Button *)0;

static void cb_btn_fskio_clear(Fl_Button*, void*) {
  if (Fl::event_state(FL_SHIFT))
    FSK_clear_sent_text();
  else
    FSK_clear_text();
}

Fl_Light_Button *btn_fskioSEND=(Fl_Light_Button *)0;

static void cb_btn_fskioSEND(Fl_Light_Button* o, void*) {
  FSK_send_text(o->value());
}

static void cb_FSK_btn_msg(Fl_Button*, void*) {
  FSK_exec_msg(0);
}

static void cb_FSK_btn_msg1(Fl_Button*, void*) {
  FSK_exec_msg(1);
}

static void cb_FSK_btn_msg2(Fl_Button*, void*) {
  FSK_exec_msg(2);
}

static void cb_FSK_btn_msg3(Fl_Button*, void*) {
  FSK_exec_msg(3);
}

static void cb_FSK_btn_msg4(Fl_Button*, void*) {
  FSK_exec_msg(4);
}

static void cb_FSK_btn_msg5(Fl_Button*, void*) {
  FSK_exec_msg(5);
}

static void cb_FSK_btn_msg6(Fl_Button*, void*) {
  FSK_exec_msg(6);
}

static void cb_FSK_btn_msg7(Fl_Button*, void*) {
  FSK_exec_msg(7);
}

static void cb_FSK_btn_msg8(Fl_Button*, void*) {
  FSK_exec_msg(8);
}

static void cb_FSK_btn_msg9(Fl_Button*, void*) {
  FSK_exec_msg(9);
}

static void cb_FSK_btn_msga(Fl_Button*, void*) {
  FSK_exec_msg(10);
}

Fl_Button *FSK_btn_msg[12]={(Fl_Button *)0};

static void cb_FSK_btn_msgb(Fl_Button*, void*) {
  FSK_exec_msg(11);
}

Fl_Double_Window* fskio_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(672, 213, gettext("FSK keying"));
    w = o; (void)w;
    { FTextView* o = FSK_sent_text = new FTextView(1, 2, 667, 90);
      FSK_sent_text->box(FL_DOWN_FRAME);
      FSK_sent_text->color((Fl_Color)20);
      FSK_sent_text->selection_color(FL_SELECTION_COLOR);
      FSK_sent_text->labeltype(FL_NORMAL_LABEL);
      FSK_sent_text->labelfont(0);
      FSK_sent_text->labelsize(14);
      FSK_sent_text->labelcolor(FL_FOREGROUND_COLOR);
      FSK_sent_text->textfont(13);
      FSK_sent_text->textsize(16);
      FSK_sent_text->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
      FSK_sent_text->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(FSK_sent_text);
      o->color(progStatus.fsk_sent_bkgnd_color);
      o->textfont(progStatus.fsk_sent_text_font); o->textsize(progStatus.fsk_sent_text_size);
      o->setFontColor(progStatus.fsk_sent_font_color);
    } // FTextView* FSK_sent_text
    { FTextEdit* o = FSK_txt_to_send = new FTextEdit(1, 94, 668, 50);
      FSK_txt_to_send->box(FL_DOWN_BOX);
      FSK_txt_to_send->color(FL_SELECTION_COLOR);
      FSK_txt_to_send->selection_color(FL_SELECTION_COLOR);
      FSK_txt_to_send->labeltype(FL_NORMAL_LABEL);
      FSK_txt_to_send->labelfont(0);
      FSK_txt_to_send->labelsize(14);
      FSK_txt_to_send->labelcolor(FL_FOREGROUND_COLOR);
      FSK_txt_to_send->textfont(13);
      FSK_txt_to_send->textsize(16);
      FSK_txt_to_send->callback((Fl_Callback*)cb_FSK_txt_to_send);
      FSK_txt_to_send->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      FSK_txt_to_send->when(FL_WHEN_CHANGED);
      o->color(progStatus.fsk_txt_to_send_bkgnd_color);
      o->textfont(progStatus.fsk_txt_to_send_font); o->textsize(progStatus.fsk_txt_to_send_size);
      o->setFontColor(progStatus.fsk_txt_to_send_font_color);
    } // FTextEdit* FSK_txt_to_send
    { Fl_Group* o = new Fl_Group(0, 146, 667, 62);
      { btn_fskio_config = new Fl_Button(374, 149, 60, 22, gettext("Config"));
        btn_fskio_config->tooltip(gettext("Open FSK configuration dialog"));
        btn_fskio_config->callback((Fl_Callback*)cb_btn_fskio_config);
      } // Fl_Button* btn_fskio_config
      { btn_fskio_clear = new Fl_Button(473, 149, 60, 22, gettext("Clear"));
        btn_fskio_clear->tooltip(gettext("Clear PENDING text\nShift - Clear SENT text"));
        btn_fskio_clear->callback((Fl_Callback*)cb_btn_fskio_clear);
      } // Fl_Button* btn_fskio_clear
      { btn_fskioSEND = new Fl_Light_Button(557, 149, 105, 22, gettext("Xmt / Rcv"));
        btn_fskioSEND->tooltip(gettext("Send / Pause sending characters"));
        btn_fskioSEND->callback((Fl_Callback*)cb_btn_fskioSEND);
      } // Fl_Light_Button* btn_fskioSEND
      { Fl_Group* o = new Fl_Group(2, 173, 220, 35);
        o->box(FL_ENGRAVED_BOX);
        { FSK_btn_msg[0] = new Fl_Button(5, 179, 50, 22, gettext("F 1"));
          FSK_btn_msg[0]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[0]->callback((Fl_Callback*)cb_FSK_btn_msg);
        } // Fl_Button* FSK_btn_msg[0]
        { FSK_btn_msg[1] = new Fl_Button(59, 179, 50, 22, gettext("F 2"));
          FSK_btn_msg[1]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[1]->callback((Fl_Callback*)cb_FSK_btn_msg1);
        } // Fl_Button* FSK_btn_msg[1]
        { FSK_btn_msg[2] = new Fl_Button(113, 179, 50, 22, gettext("F 3"));
          FSK_btn_msg[2]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[2]->callback((Fl_Callback*)cb_FSK_btn_msg2);
        } // Fl_Button* FSK_btn_msg[2]
        { FSK_btn_msg[3] = new Fl_Button(168, 179, 50, 22, gettext("F 4"));
          FSK_btn_msg[3]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[3]->callback((Fl_Callback*)cb_FSK_btn_msg3);
        } // Fl_Button* FSK_btn_msg[3]
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(225, 173, 220, 35);
        o->box(FL_ENGRAVED_BOX);
        { FSK_btn_msg[4] = new Fl_Button(229, 179, 50, 22, gettext("F 5"));
          FSK_btn_msg[4]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[4]->callback((Fl_Callback*)cb_FSK_btn_msg4);
        } // Fl_Button* FSK_btn_msg[4]
        { FSK_btn_msg[5] = new Fl_Button(283, 179, 50, 22, gettext("F 6"));
          FSK_btn_msg[5]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[5]->callback((Fl_Callback*)cb_FSK_btn_msg5);
        } // Fl_Button* FSK_btn_msg[5]
        { FSK_btn_msg[6] = new Fl_Button(337, 179, 50, 22, gettext("F 7"));
          FSK_btn_msg[6]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[6]->callback((Fl_Callback*)cb_FSK_btn_msg6);
        } // Fl_Button* FSK_btn_msg[6]
        { FSK_btn_msg[7] = new Fl_Button(391, 179, 50, 22, gettext("F 8"));
          FSK_btn_msg[7]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[7]->callback((Fl_Callback*)cb_FSK_btn_msg7);
        } // Fl_Button* FSK_btn_msg[7]
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(448, 173, 219, 35);
        o->box(FL_ENGRAVED_BOX);
        { FSK_btn_msg[8] = new Fl_Button(451, 179, 50, 22, gettext("F 9"));
          FSK_btn_msg[8]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[8]->callback((Fl_Callback*)cb_FSK_btn_msg8);
        } // Fl_Button* FSK_btn_msg[8]
        { FSK_btn_msg[9] = new Fl_Button(505, 179, 50, 22, gettext("F 10"));
          FSK_btn_msg[9]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[9]->callback((Fl_Callback*)cb_FSK_btn_msg9);
        } // Fl_Button* FSK_btn_msg[9]
        { FSK_btn_msg[10] = new Fl_Button(559, 179, 50, 22, gettext("F 11"));
          FSK_btn_msg[10]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[10]->callback((Fl_Callback*)cb_FSK_btn_msga);
        } // Fl_Button* FSK_btn_msg[10]
        { FSK_btn_msg[11] = new Fl_Button(614, 179, 50, 22, gettext("F 12"));
          FSK_btn_msg[11]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          FSK_btn_msg[11]->callback((Fl_Callback*)cb_FSK_btn_msgb);
        } // Fl_Button* FSK_btn_msg[11]
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}

static void cb_FSK_edit_label(Fl_Input2*, void*) {
  FSK_label_cb(1);
}

static void cb_FSK_edit_msg(Fl_Input2*, void*) {
  FSK_msg_cb(1);
}

static void cb_FSK_edit_label1(Fl_Input2*, void*) {
  FSK_label_cb(2);
}

static void cb_FSK_edit_msg1(Fl_Input2*, void*) {
  FSK_msg_cb(2);
}

static void cb_FSK_edit_label2(Fl_Input2*, void*) {
  FSK_label_cb(3);
}

static void cb_FSK_edit_msg2(Fl_Input2*, void*) {
  FSK_msg_cb(3);
}

static void cb_FSK_edit_label3(Fl_Input2*, void*) {
  FSK_label_cb(4);
}

static void cb_FSK_edit_msg3(Fl_Input2*, void*) {
  FSK_msg_cb(4);
}

static void cb_FSK_edit_label4(Fl_Input2*, void*) {
  FSK_label_cb(5);
}

static void cb_FSK_edit_msg4(Fl_Input2*, void*) {
  FSK_msg_cb(5);
}

static void cb_FSK_edit_label5(Fl_Input2*, void*) {
  FSK_label_cb(6);
}

static void cb_FSK_edit_msg5(Fl_Input2*, void*) {
  FSK_msg_cb(6);
}

static void cb_FSK_edit_label6(Fl_Input2*, void*) {
  FSK_label_cb(7);
}

static void cb_FSK_edit_msg6(Fl_Input2*, void*) {
  FSK_msg_cb(7);
}

static void cb_FSK_edit_label7(Fl_Input2*, void*) {
  FSK_label_cb(8);
}

static void cb_FSK_edit_msg7(Fl_Input2*, void*) {
  FSK_msg_cb(8);
}

static void cb_FSK_edit_label8(Fl_Input2*, void*) {
  FSK_label_cb(9);
}

static void cb_FSK_edit_msg8(Fl_Input2*, void*) {
  FSK_msg_cb(9);
}

static void cb_FSK_edit_label9(Fl_Input2*, void*) {
  FSK_label_cb(10);
}

static void cb_FSK_edit_msg9(Fl_Input2*, void*) {
  FSK_msg_cb(10);
}

static void cb_FSK_edit_labela(Fl_Input2*, void*) {
  FSK_label_cb(11);
}

static void cb_FSK_edit_msga(Fl_Input2*, void*) {
  FSK_msg_cb(11);
}

Fl_Input2 *FSK_edit_label[12]={(Fl_Input2 *)0};

static void cb_FSK_edit_labelb(Fl_Input2*, void*) {
  FSK_label_cb(12);
}

Fl_Input2 *FSK_edit_msg[12]={(Fl_Input2 *)0};

static void cb_FSK_edit_msgb(Fl_Input2*, void*) {
  FSK_msg_cb(12);
}

Fl_Button *FSK_btn_cancel_edit=(Fl_Button *)0;

static void cb_FSK_btn_cancel_edit(Fl_Button*, void*) {
  FSK_cancel_edit();
}

Fl_Button *FSK_btn_apply_edit=(Fl_Button *)0;

static void cb_FSK_btn_apply_edit(Fl_Button*, void*) {
  FSK_apply_edit();
}

Fl_Button *FSK_btn_FSK_done_edit=(Fl_Button *)0;

static void cb_FSK_btn_FSK_done_edit(Fl_Button*, void*) {
  FSK_done_edit();
}

Fl_Double_Window* FSK_make_message_editor() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(670, 344, gettext("FSK Message Editor"));
    w = o; (void)w;
    { Fl_Tabs* o = new Fl_Tabs(0, 0, 570, 345);
      o->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
      { Fl_Group* o = new Fl_Group(0, 25, 570, 320, gettext("F1-F4"));
        o->hide();
        { new Fl_Box(22, 30, 84, 20, gettext("Label"));
        } // Fl_Box* o
        { new Fl_Box(211, 30, 223, 20, gettext("Message Text"));
        } // Fl_Box* o
        { FSK_edit_label[0] = new Fl_Input2(5, 74, 80, 22, gettext("F1"));
          FSK_edit_label[0]->box(FL_DOWN_BOX);
          FSK_edit_label[0]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[0]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[0]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[0]->labelfont(0);
          FSK_edit_label[0]->labelsize(14);
          FSK_edit_label[0]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[0]->callback((Fl_Callback*)cb_FSK_edit_label);
          FSK_edit_label[0]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[0]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[0]
        { FSK_edit_msg[0] = new Fl_Input2(90, 55, 475, 65);
          FSK_edit_msg[0]->type(4);
          FSK_edit_msg[0]->box(FL_DOWN_BOX);
          FSK_edit_msg[0]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[0]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[0]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[0]->labelfont(0);
          FSK_edit_msg[0]->labelsize(14);
          FSK_edit_msg[0]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[0]->callback((Fl_Callback*)cb_FSK_edit_msg);
          FSK_edit_msg[0]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[0]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[0]
        { FSK_edit_label[1] = new Fl_Input2(5, 144, 80, 22, gettext("F2"));
          FSK_edit_label[1]->box(FL_DOWN_BOX);
          FSK_edit_label[1]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[1]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[1]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[1]->labelfont(0);
          FSK_edit_label[1]->labelsize(14);
          FSK_edit_label[1]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[1]->callback((Fl_Callback*)cb_FSK_edit_label1);
          FSK_edit_label[1]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[1]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[1]
        { FSK_edit_msg[1] = new Fl_Input2(90, 125, 475, 65);
          FSK_edit_msg[1]->type(4);
          FSK_edit_msg[1]->box(FL_DOWN_BOX);
          FSK_edit_msg[1]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[1]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[1]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[1]->labelfont(0);
          FSK_edit_msg[1]->labelsize(14);
          FSK_edit_msg[1]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[1]->callback((Fl_Callback*)cb_FSK_edit_msg1);
          FSK_edit_msg[1]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[1]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[1]
        { FSK_edit_label[2] = new Fl_Input2(5, 214, 80, 22, gettext("F3"));
          FSK_edit_label[2]->box(FL_DOWN_BOX);
          FSK_edit_label[2]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[2]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[2]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[2]->labelfont(0);
          FSK_edit_label[2]->labelsize(14);
          FSK_edit_label[2]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[2]->callback((Fl_Callback*)cb_FSK_edit_label2);
          FSK_edit_label[2]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[2]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[2]
        { FSK_edit_msg[2] = new Fl_Input2(90, 195, 475, 65);
          FSK_edit_msg[2]->type(4);
          FSK_edit_msg[2]->box(FL_DOWN_BOX);
          FSK_edit_msg[2]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[2]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[2]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[2]->labelfont(0);
          FSK_edit_msg[2]->labelsize(14);
          FSK_edit_msg[2]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[2]->callback((Fl_Callback*)cb_FSK_edit_msg2);
          FSK_edit_msg[2]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[2]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[2]
        { FSK_edit_label[3] = new Fl_Input2(5, 284, 80, 22, gettext("F4"));
          FSK_edit_label[3]->box(FL_DOWN_BOX);
          FSK_edit_label[3]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[3]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[3]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[3]->labelfont(0);
          FSK_edit_label[3]->labelsize(14);
          FSK_edit_label[3]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[3]->callback((Fl_Callback*)cb_FSK_edit_label3);
          FSK_edit_label[3]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[3]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[3]
        { FSK_edit_msg[3] = new Fl_Input2(90, 265, 475, 65);
          FSK_edit_msg[3]->type(4);
          FSK_edit_msg[3]->box(FL_DOWN_BOX);
          FSK_edit_msg[3]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[3]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[3]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[3]->labelfont(0);
          FSK_edit_msg[3]->labelsize(14);
          FSK_edit_msg[3]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[3]->callback((Fl_Callback*)cb_FSK_edit_msg3);
          FSK_edit_msg[3]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[3]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[3]
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 25, 570, 320, gettext("F5-f8"));
        o->hide();
        { new Fl_Box(24, 30, 90, 20, gettext("Label"));
        } // Fl_Box* o
        { new Fl_Box(227, 30, 240, 20, gettext("Message Text"));
        } // Fl_Box* o
        { FSK_edit_label[4] = new Fl_Input2(5, 74, 80, 22, gettext("F5"));
          FSK_edit_label[4]->box(FL_DOWN_BOX);
          FSK_edit_label[4]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[4]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[4]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[4]->labelfont(0);
          FSK_edit_label[4]->labelsize(14);
          FSK_edit_label[4]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[4]->callback((Fl_Callback*)cb_FSK_edit_label4);
          FSK_edit_label[4]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[4]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[4]
        { FSK_edit_msg[4] = new Fl_Input2(90, 55, 475, 65);
          FSK_edit_msg[4]->type(4);
          FSK_edit_msg[4]->box(FL_DOWN_BOX);
          FSK_edit_msg[4]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[4]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[4]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[4]->labelfont(0);
          FSK_edit_msg[4]->labelsize(14);
          FSK_edit_msg[4]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[4]->callback((Fl_Callback*)cb_FSK_edit_msg4);
          FSK_edit_msg[4]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[4]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[4]
        { FSK_edit_label[5] = new Fl_Input2(5, 144, 80, 22, gettext("F6"));
          FSK_edit_label[5]->box(FL_DOWN_BOX);
          FSK_edit_label[5]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[5]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[5]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[5]->labelfont(0);
          FSK_edit_label[5]->labelsize(14);
          FSK_edit_label[5]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[5]->callback((Fl_Callback*)cb_FSK_edit_label5);
          FSK_edit_label[5]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[5]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[5]
        { FSK_edit_msg[5] = new Fl_Input2(90, 125, 475, 65);
          FSK_edit_msg[5]->type(4);
          FSK_edit_msg[5]->box(FL_DOWN_BOX);
          FSK_edit_msg[5]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[5]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[5]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[5]->labelfont(0);
          FSK_edit_msg[5]->labelsize(14);
          FSK_edit_msg[5]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[5]->callback((Fl_Callback*)cb_FSK_edit_msg5);
          FSK_edit_msg[5]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[5]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[5]
        { FSK_edit_label[6] = new Fl_Input2(5, 214, 80, 22, gettext("F7"));
          FSK_edit_label[6]->box(FL_DOWN_BOX);
          FSK_edit_label[6]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[6]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[6]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[6]->labelfont(0);
          FSK_edit_label[6]->labelsize(14);
          FSK_edit_label[6]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[6]->callback((Fl_Callback*)cb_FSK_edit_label6);
          FSK_edit_label[6]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[6]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[6]
        { FSK_edit_msg[6] = new Fl_Input2(90, 195, 475, 65);
          FSK_edit_msg[6]->type(4);
          FSK_edit_msg[6]->box(FL_DOWN_BOX);
          FSK_edit_msg[6]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[6]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[6]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[6]->labelfont(0);
          FSK_edit_msg[6]->labelsize(14);
          FSK_edit_msg[6]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[6]->callback((Fl_Callback*)cb_FSK_edit_msg6);
          FSK_edit_msg[6]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[6]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[6]
        { FSK_edit_label[7] = new Fl_Input2(5, 284, 80, 22, gettext("F8"));
          FSK_edit_label[7]->box(FL_DOWN_BOX);
          FSK_edit_label[7]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[7]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[7]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[7]->labelfont(0);
          FSK_edit_label[7]->labelsize(14);
          FSK_edit_label[7]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[7]->callback((Fl_Callback*)cb_FSK_edit_label7);
          FSK_edit_label[7]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[7]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[7]
        { FSK_edit_msg[7] = new Fl_Input2(90, 265, 475, 65);
          FSK_edit_msg[7]->type(4);
          FSK_edit_msg[7]->box(FL_DOWN_BOX);
          FSK_edit_msg[7]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[7]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[7]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[7]->labelfont(0);
          FSK_edit_msg[7]->labelsize(14);
          FSK_edit_msg[7]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[7]->callback((Fl_Callback*)cb_FSK_edit_msg7);
          FSK_edit_msg[7]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[7]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[7]
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 25, 570, 320, gettext("F9-F12"));
        { new Fl_Box(24, 30, 90, 20, gettext("Label"));
        } // Fl_Box* o
        { new Fl_Box(227, 30, 240, 20, gettext("Message Text"));
        } // Fl_Box* o
        { FSK_edit_label[8] = new Fl_Input2(5, 73, 80, 22, gettext("F9"));
          FSK_edit_label[8]->box(FL_DOWN_BOX);
          FSK_edit_label[8]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[8]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[8]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[8]->labelfont(0);
          FSK_edit_label[8]->labelsize(14);
          FSK_edit_label[8]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[8]->callback((Fl_Callback*)cb_FSK_edit_label8);
          FSK_edit_label[8]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[8]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[8]
        { FSK_edit_msg[8] = new Fl_Input2(90, 55, 475, 65);
          FSK_edit_msg[8]->type(4);
          FSK_edit_msg[8]->box(FL_DOWN_BOX);
          FSK_edit_msg[8]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[8]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[8]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[8]->labelfont(0);
          FSK_edit_msg[8]->labelsize(14);
          FSK_edit_msg[8]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[8]->callback((Fl_Callback*)cb_FSK_edit_msg8);
          FSK_edit_msg[8]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[8]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[8]
        { FSK_edit_label[9] = new Fl_Input2(5, 143, 80, 22, gettext("F10"));
          FSK_edit_label[9]->box(FL_DOWN_BOX);
          FSK_edit_label[9]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[9]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[9]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[9]->labelfont(0);
          FSK_edit_label[9]->labelsize(14);
          FSK_edit_label[9]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[9]->callback((Fl_Callback*)cb_FSK_edit_label9);
          FSK_edit_label[9]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[9]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[9]
        { FSK_edit_msg[9] = new Fl_Input2(90, 125, 475, 65);
          FSK_edit_msg[9]->type(4);
          FSK_edit_msg[9]->box(FL_DOWN_BOX);
          FSK_edit_msg[9]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[9]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[9]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[9]->labelfont(0);
          FSK_edit_msg[9]->labelsize(14);
          FSK_edit_msg[9]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[9]->callback((Fl_Callback*)cb_FSK_edit_msg9);
          FSK_edit_msg[9]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[9]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[9]
        { FSK_edit_label[10] = new Fl_Input2(5, 213, 80, 22, gettext("F11"));
          FSK_edit_label[10]->box(FL_DOWN_BOX);
          FSK_edit_label[10]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[10]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[10]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[10]->labelfont(0);
          FSK_edit_label[10]->labelsize(14);
          FSK_edit_label[10]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[10]->callback((Fl_Callback*)cb_FSK_edit_labela);
          FSK_edit_label[10]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[10]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[10]
        { FSK_edit_msg[10] = new Fl_Input2(90, 195, 475, 65);
          FSK_edit_msg[10]->type(4);
          FSK_edit_msg[10]->box(FL_DOWN_BOX);
          FSK_edit_msg[10]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[10]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[10]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[10]->labelfont(0);
          FSK_edit_msg[10]->labelsize(14);
          FSK_edit_msg[10]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[10]->callback((Fl_Callback*)cb_FSK_edit_msga);
          FSK_edit_msg[10]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[10]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[10]
        { FSK_edit_label[11] = new Fl_Input2(5, 283, 80, 22, gettext("F12"));
          FSK_edit_label[11]->box(FL_DOWN_BOX);
          FSK_edit_label[11]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_label[11]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_label[11]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_label[11]->labelfont(0);
          FSK_edit_label[11]->labelsize(14);
          FSK_edit_label[11]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_label[11]->callback((Fl_Callback*)cb_FSK_edit_labelb);
          FSK_edit_label[11]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          FSK_edit_label[11]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_label[11]
        { FSK_edit_msg[11] = new Fl_Input2(90, 265, 475, 65);
          FSK_edit_msg[11]->type(4);
          FSK_edit_msg[11]->box(FL_DOWN_BOX);
          FSK_edit_msg[11]->color(FL_BACKGROUND2_COLOR);
          FSK_edit_msg[11]->selection_color(FL_SELECTION_COLOR);
          FSK_edit_msg[11]->labeltype(FL_NORMAL_LABEL);
          FSK_edit_msg[11]->labelfont(0);
          FSK_edit_msg[11]->labelsize(14);
          FSK_edit_msg[11]->labelcolor(FL_FOREGROUND_COLOR);
          FSK_edit_msg[11]->callback((Fl_Callback*)cb_FSK_edit_msgb);
          FSK_edit_msg[11]->align(Fl_Align(FL_ALIGN_LEFT));
          FSK_edit_msg[11]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* FSK_edit_msg[11]
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    { Fl_Group* o = new Fl_Group(575, 27, 90, 43);
      o->box(FL_ENGRAVED_FRAME);
      { new Fl_Box(579, 29, 82, 20, gettext("\'[\' Send"));
      } // Fl_Box* o
      { new Fl_Box(579, 49, 82, 20, gettext("\']\' Recv"));
      } // Fl_Box* o
      o->end();
    } // Fl_Group* o
    { FSK_btn_cancel_edit = new Fl_Button(575, 88, 90, 22, gettext("Cancel"));
      FSK_btn_cancel_edit->tooltip(gettext("Exit editor, discard changes"));
      FSK_btn_cancel_edit->callback((Fl_Callback*)cb_FSK_btn_cancel_edit);
    } // Fl_Button* FSK_btn_cancel_edit
    { FSK_btn_apply_edit = new Fl_Button(575, 114, 90, 22, gettext("Apply"));
      FSK_btn_apply_edit->tooltip(gettext("Apply current changes to function keys"));
      FSK_btn_apply_edit->callback((Fl_Callback*)cb_FSK_btn_apply_edit);
    } // Fl_Button* FSK_btn_apply_edit
    { FSK_btn_FSK_done_edit = new Fl_Button(575, 141, 90, 22, gettext("Close"));
      FSK_btn_FSK_done_edit->tooltip(gettext("Apply changes and close editor"));
      FSK_btn_FSK_done_edit->callback((Fl_Callback*)cb_FSK_btn_FSK_done_edit);
    } // Fl_Button* FSK_btn_FSK_done_edit
    o->resizable(o);
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_ComboBox *select_fskioPORT=(Fl_ComboBox *)0;

static void cb_select_fskioPORT(Fl_ComboBox* o, void*) {
  progStatus.FSK_PORT = o->value();
}

Fl_Light_Button *btn_fskioCONNECT=(Fl_Light_Button *)0;

static void cb_btn_fskioCONNECT(Fl_Light_Button* o, void*) {
  if (o->value() == 0) {
    FSK_close_port();
    btn_fskioCAT->activate();
    btn_fskioAUX->activate();
    btn_fskioSEP->activate();
    progStatus.FSK_CONNECTED = 0;
  }
  else if (!FSK_open_port()) {
    o->value(0);
    btn_fskioCAT->activate();
    btn_fskioAUX->activate();
    btn_fskioSEP->activate();
    progStatus.FSK_CONNECTED = 0;
  } else {
    btn_fskioCAT->value(0); btn_fskioCAT->deactivate();
    btn_fskioAUX->value(0); btn_fskioAUX->deactivate();
    btn_fskioSEP->value(0); btn_fskioSEP->deactivate();
    progStatus.FSK_CONNECTED = 1;
  }
  FSK_open_port();
  progStatus.FSK_SHARED = FSK_USES_FSK;
}

Fl_Check_Button *btn_fskioCAT=(Fl_Check_Button *)0;

static void cb_btn_fskioCAT(Fl_Check_Button* o, void*) {
  if (o->value()) {
    progStatus.FSK_SHARED = FSK_USES_CAT;
    btn_fskioAUX->value(0); btn_fskioAUX->deactivate();
    btn_fskioSEP->value(0); btn_fskioSEP->deactivate();
    btn_fskioCONNECT->value(0); btn_fskioCONNECT->deactivate();
    btn_fskioSHARED->value(0); btn_fskioSHARED->deactivate();
    select_fskioPORT->value("NONE"); select_fskioPORT->deactivate();
  }else {
    progStatus.FSK_SHARED = FSK_USES_FSK;
    btn_fskioCONNECT->activate();
    btn_fskioAUX->activate();
    btn_fskioCAT->activate();
    btn_fskioSEP->activate();
    btn_fskioSHARED->activate();
    select_fskioPORT->activate();
  }
}

Fl_Check_Button *btn_fskioAUX=(Fl_Check_Button *)0;

static void cb_btn_fskioAUX(Fl_Check_Button* o, void*) {
  if (o->value()) {
    progStatus.FSK_SHARED = FSK_USES_AUX;
    btn_fskioCAT->value(0); btn_fskioCAT->deactivate();
    btn_fskioSEP->value(0); btn_fskioSEP->deactivate();
    btn_fskioCONNECT->value(0); btn_fskioCONNECT->deactivate();
    btn_fskioSHARED->value(0); btn_fskioSHARED->deactivate();
    select_fskioPORT->value("NONE"); select_fskioPORT->deactivate();
  }else {
    progStatus.FSK_SHARED = FSK_USES_FSK;
    btn_fskioCONNECT->activate();
    btn_fskioAUX->activate();
    btn_fskioCAT->activate();
    btn_fskioSEP->activate();
    btn_fskioSHARED->activate();
    select_fskioPORT->activate();
  }
}

Fl_Check_Button *btn_fskioSEP=(Fl_Check_Button *)0;

static void cb_btn_fskioSEP(Fl_Check_Button* o, void*) {
  if (o->value()) {
    progStatus.FSK_SHARED = FSK_USES_SEP;
    btn_fskioAUX->value(0); btn_fskioAUX->deactivate();
    btn_fskioCAT->value(0); btn_fskioCAT->deactivate();
    btn_fskioCONNECT->value(0); btn_fskioCONNECT->deactivate();
    btn_fskioSHARED->value(0); btn_fskioSHARED->deactivate();
    select_fskioPORT->value("NONE"); select_fskioPORT->deactivate();
  }else {
    progStatus.FSK_SHARED = FSK_USES_FSK;
    btn_fskioCONNECT->activate();
    btn_fskioAUX->activate();
    btn_fskioCAT->activate();
    btn_fskioSEP->activate();
    btn_fskioSHARED->activate();
    select_fskioPORT->activate();
  }
}

Fl_Check_Button *btn_fskioSHARED=(Fl_Check_Button *)0;

static void cb_btn_fskioSHARED(Fl_Check_Button* o, void*) {
  if (o->value()) {
    progStatus.FSK_SHARED = FSK_USES_CWIO;
    btn_fskioAUX->value(0); btn_fskioAUX->deactivate();
    btn_fskioCAT->value(0); btn_fskioCAT->deactivate();
    btn_fskioSEP->value(0); btn_fskioSEP->deactivate();
    btn_fskioCONNECT->value(0); btn_fskioCONNECT->deactivate();
    select_fskioPORT->value("NONE"); select_fskioPORT->deactivate();
  }else {
    progStatus.FSK_SHARED = FSK_USES_FSK;
    btn_fskioCONNECT->activate();
    btn_fskioAUX->activate();
    btn_fskioCAT->activate();
    btn_fskioSEP->activate();
    btn_fskioSHARED->activate();
    select_fskioPORT->activate();
  }
}

Fl_Check_Button *btn_fskioINVERTED=(Fl_Check_Button *)0;

static void cb_btn_fskioINVERTED(Fl_Check_Button* o, void*) {
  progStatus.FSK_INVERTED = o->value();
}

Fl_Check_Button *btn_fskioSTOPBITS=(Fl_Check_Button *)0;

static void cb_btn_fskioSTOPBITS(Fl_Check_Button* o, void*) {
  progStatus.FSK_STOPBITS = o->value();
}

Fl_ListBox *listbox_fskioKEYLINE=(Fl_ListBox *)0;

static void cb_listbox_fskioKEYLINE(Fl_ListBox* o, void*) {
  progStatus.FSK_KEYLINE = o->index();
}

Fl_Spinner *cntr_fskioPTT=(Fl_Spinner *)0;

static void cb_cntr_fskioPTT(Fl_Spinner* o, void*) {
  progStatus.FSK_PTT = o->value();
}

Fl_Counter *fsk_idles=(Fl_Counter *)0;

static void cb_fsk_idles(Fl_Counter* o, void*) {
  progStatus.fsk_idles = o->value();
}

Fl_Double_Window* fskio_config_dialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(670, 100, gettext("FSK Configuration"));
    w = o; (void)w;
    { Fl_Group* o = new Fl_Group(2, 3, 666, 100);
      o->box(FL_ENGRAVED_FRAME);
      { Fl_ComboBox* o = select_fskioPORT = new Fl_ComboBox(73, 73, 496, 23, gettext("Ser. Port"));
        select_fskioPORT->tooltip(gettext("FSKIO serial port"));
        select_fskioPORT->box(FL_DOWN_BOX);
        select_fskioPORT->color((Fl_Color)53);
        select_fskioPORT->selection_color(FL_BACKGROUND_COLOR);
        select_fskioPORT->labeltype(FL_NORMAL_LABEL);
        select_fskioPORT->labelfont(0);
        select_fskioPORT->labelsize(14);
        select_fskioPORT->labelcolor(FL_FOREGROUND_COLOR);
        select_fskioPORT->callback((Fl_Callback*)cb_select_fskioPORT);
        select_fskioPORT->align(Fl_Align(FL_ALIGN_LEFT));
        select_fskioPORT->when(FL_WHEN_RELEASE);
        o->value(progStatus.FSK_PORT.c_str());
        select_fskioPORT->end();
      } // Fl_ComboBox* select_fskioPORT
      { Fl_Light_Button* o = btn_fskioCONNECT = new Fl_Light_Button(578, 73, 80, 23, gettext("Connect"));
        btn_fskioCONNECT->callback((Fl_Callback*)cb_btn_fskioCONNECT);
        o->value(progStatus.FSK_CONNECTED);
      } // Fl_Light_Button* btn_fskioCONNECT
      { Fl_Check_Button* o = btn_fskioCAT = new Fl_Check_Button(87, 15, 23, 15, gettext("Use CAT"));
        btn_fskioCAT->tooltip(gettext("Use DTR/RTS on CAT serial port"));
        btn_fskioCAT->down_box(FL_DOWN_BOX);
        btn_fskioCAT->callback((Fl_Callback*)cb_btn_fskioCAT);
        btn_fskioCAT->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.FSK_SHARED == FSK_USES_CAT);
      } // Fl_Check_Button* btn_fskioCAT
      { Fl_Check_Button* o = btn_fskioAUX = new Fl_Check_Button(88, 46, 23, 15, gettext("Use AUX"));
        btn_fskioAUX->tooltip(gettext("Use DTR/RTS on Auxiliary serial port"));
        btn_fskioAUX->down_box(FL_DOWN_BOX);
        btn_fskioAUX->callback((Fl_Callback*)cb_btn_fskioAUX);
        btn_fskioAUX->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.FSK_SHARED == FSK_USES_AUX);
      } // Fl_Check_Button* btn_fskioAUX
      { Fl_Check_Button* o = btn_fskioSEP = new Fl_Check_Button(212, 15, 23, 15, gettext("Use SEP"));
        btn_fskioSEP->tooltip(gettext("Use DTR/RTS Separate serial port"));
        btn_fskioSEP->down_box(FL_DOWN_BOX);
        btn_fskioSEP->callback((Fl_Callback*)cb_btn_fskioSEP);
        btn_fskioSEP->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.FSK_SHARED == FSK_USES_SEP);
      } // Fl_Check_Button* btn_fskioSEP
      { Fl_Check_Button* o = btn_fskioSHARED = new Fl_Check_Button(212, 46, 23, 15, gettext("CWIO shared"));
        btn_fskioSHARED->tooltip(gettext("Use DTR/RTS fskio shared port"));
        btn_fskioSHARED->down_box(FL_DOWN_BOX);
        btn_fskioSHARED->callback((Fl_Callback*)cb_btn_fskioSHARED);
        btn_fskioSHARED->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.FSK_SHARED == FSK_USES_CWIO);
      } // Fl_Check_Button* btn_fskioSHARED
      { Fl_Check_Button* o = btn_fskioINVERTED = new Fl_Check_Button(339, 15, 23, 15, gettext("Inverted"));
        btn_fskioINVERTED->tooltip(gettext("DTR/RTS signaling is inverted\n(-) keying"));
        btn_fskioINVERTED->down_box(FL_DOWN_BOX);
        btn_fskioINVERTED->callback((Fl_Callback*)cb_btn_fskioINVERTED);
        btn_fskioINVERTED->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.FSK_INVERTED);
      } // Fl_Check_Button* btn_fskioINVERTED
      { Fl_Check_Button* o = btn_fskioSTOPBITS = new Fl_Check_Button(339, 46, 23, 15, gettext("1.5 stop bits"));
        btn_fskioSTOPBITS->tooltip(gettext("Enabled - 1.5 stop bits\nDisable - 2 stop bits"));
        btn_fskioSTOPBITS->down_box(FL_DOWN_BOX);
        btn_fskioSTOPBITS->callback((Fl_Callback*)cb_btn_fskioSTOPBITS);
        btn_fskioSTOPBITS->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.FSK_STOPBITS);
      } // Fl_Check_Button* btn_fskioSTOPBITS
      { Fl_ListBox* o = listbox_fskioKEYLINE = new Fl_ListBox(593, 41, 65, 24, gettext("FSK Keyline"));
        listbox_fskioKEYLINE->tooltip(gettext("Select either DTR or RTS for keyline"));
        listbox_fskioKEYLINE->box(FL_DOWN_BOX);
        listbox_fskioKEYLINE->color(FL_BACKGROUND2_COLOR);
        listbox_fskioKEYLINE->selection_color(FL_BACKGROUND_COLOR);
        listbox_fskioKEYLINE->labeltype(FL_NORMAL_LABEL);
        listbox_fskioKEYLINE->labelfont(0);
        listbox_fskioKEYLINE->labelsize(14);
        listbox_fskioKEYLINE->labelcolor(FL_FOREGROUND_COLOR);
        listbox_fskioKEYLINE->callback((Fl_Callback*)cb_listbox_fskioKEYLINE);
        listbox_fskioKEYLINE->align(Fl_Align(FL_ALIGN_LEFT));
        listbox_fskioKEYLINE->when(FL_WHEN_RELEASE);
        o->add("None|RTS|DTR");
        o->index(progStatus.FSK_KEYLINE);
        listbox_fskioKEYLINE->end();
      } // Fl_ListBox* listbox_fskioKEYLINE
      { Fl_Spinner* o = cntr_fskioPTT = new Fl_Spinner(608, 10, 50, 25, gettext("PTT delay"));
        cntr_fskioPTT->tooltip(gettext("PTT delay before keydown\n0 = Break-in"));
        cntr_fskioPTT->minimum(0);
        cntr_fskioPTT->value(0);
        cntr_fskioPTT->callback((Fl_Callback*)cb_cntr_fskioPTT);
        o->value(progStatus.FSK_PTT);
      } // Fl_Spinner* cntr_fskioPTT
      { Fl_Counter* o = fsk_idles = new Fl_Counter(400, 11, 80, 21, gettext("Start Idles"));
        fsk_idles->tooltip(gettext("Transmit # <LTRS> after PTT on"));
        fsk_idles->type(1);
        fsk_idles->minimum(0);
        fsk_idles->maximum(20);
        fsk_idles->step(1);
        fsk_idles->callback((Fl_Callback*)cb_fsk_idles);
        o->value(progStatus.fsk_idles);
      } // Fl_Counter* fsk_idles
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Menu_Bar *FSKlog_menubar=(Fl_Menu_Bar *)0;

static void cb_fsklog_fsk_menu_open(Fl_Menu_*, void*) {
  fsklog_open();
}

static void cb_fsklog_fsk_menu_new(Fl_Menu_*, void*) {
  fsklog_new();
}

static void cb_fsklog_fsk_menu_save(Fl_Menu_*, void*) {
  fsklog_save();
}

static void cb_fsklog_fsk_menu_save_as(Fl_Menu_*, void*) {
  fsklog_save_as();
}

static void cb_fsklog_fsk_menu_export_adif(Fl_Menu_*, void*) {
  fsklog_export_adif();
}

static void cb_fsklog_fsk_menu_import_adif(Fl_Menu_*, void*) {
  fsklog_import_adif();
}

static void cb_fsklog_fsk_menu_dupcheck(Fl_Menu_* o, void*) {
  //fsklog.dupcheck = o->value();
}

static void cb_fsklog_fsk_menu_leading_zeros(Fl_Menu_* o, void*) {
  //fsklog.dupcheck = o->value();
}

static void cb_fsklog_fsk_menu_cut_numbers(Fl_Menu_* o, void*) {
  //fsklog.cut_nbrs = o->value();
}

Fl_Menu_Item menu_FSKlog_menubar[] = {
 {gettext_noop("Files"), 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Open"), 0,  (Fl_Callback*)cb_fsklog_fsk_menu_open, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("New"), 0,  (Fl_Callback*)cb_fsklog_fsk_menu_new, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Save"), 0,  (Fl_Callback*)cb_fsklog_fsk_menu_save, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Save As"), 0,  (Fl_Callback*)cb_fsklog_fsk_menu_save_as, 0, 128, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Export ADIF"), 0,  (Fl_Callback*)cb_fsklog_fsk_menu_export_adif, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Import ADIF"), 0,  (Fl_Callback*)cb_fsklog_fsk_menu_import_adif, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {gettext_noop("Config"), 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Dup check"), 0,  (Fl_Callback*)cb_fsklog_fsk_menu_dupcheck, 0, 2, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Leading zeros"), 0,  (Fl_Callback*)cb_fsklog_fsk_menu_leading_zeros, 0, 2, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Cut numbers"), 0,  (Fl_Callback*)cb_fsklog_fsk_menu_cut_numbers, 0, 2, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Output *txt_fsklog_file=(Fl_Output *)0;

static void cb_txt_fsklog_file(Fl_Output* o, void*) {
  //progStatus.fsklogfile_name = o->value();
}

Fl_Group *fsk_grp_qso_data=(Fl_Group *)0;

Fl_Input2 *fsk_op_freq=(Fl_Input2 *)0;

Fl_Button *btn_fsklog_clear_qso=(Fl_Button *)0;

static void cb_btn_fsklog_clear_qso(Fl_Button*, void*) {
  fsklog_clear_qso();
}

Fl_Button *btn_fsklog_save_qso=(Fl_Button *)0;

static void cb_btn_fsklog_save_qso(Fl_Button*, void*) {
  fsklog_save_qso();
}

Fl_Button *btn_fsklog_edit_entry=(Fl_Button *)0;

static void cb_btn_fsklog_edit_entry(Fl_Button*, void*) {
  fsklog_edit_entry();
}

Fl_Button *btn_fsklog_delete_entry=(Fl_Button *)0;

static void cb_btn_fsklog_delete_entry(Fl_Button*, void*) {
  fsklog_delete_entry();
}

Fl_Input2 *fsk_date=(Fl_Input2 *)0;

Fl_Input2 *fsk_time=(Fl_Input2 *)0;

Fl_Input2 *fsk_rst_out=(Fl_Input2 *)0;

Fl_Input2 *fsk_rst_in=(Fl_Input2 *)0;

Fl_Input2 *fsk_xchg_in=(Fl_Input2 *)0;

Fl_Counter *cntr_fsk_log_nbr=(Fl_Counter *)0;

static void cb_cntr_fsk_log_nbr(Fl_Counter* o, void*) {
  progStatus.fsk_log_nbr = o->value();
}

Fl_Input2 *fsk_op_name=(Fl_Input2 *)0;

Fl_Input2 *fsk_op_call=(Fl_Input2 *)0;

Fl_Button *btn_fsk_datetime=(Fl_Button *)0;

static void cb_btn_fsk_datetime(Fl_Button*, void*) {
  fsklog_sort_by_datetime();
}

Fl_Button *btn_fsk_time=(Fl_Button *)0;

static void cb_btn_fsk_time(Fl_Button*, void*) {
  fsklog_sort_by_datetime();
}

Fl_Button *btn_fsk_freq=(Fl_Button *)0;

static void cb_btn_fsk_freq(Fl_Button*, void*) {
  fsklog_sort_by_freq();
}

Fl_Button *btn_fsk_call=(Fl_Button *)0;

static void cb_btn_fsk_call(Fl_Button*, void*) {
  fsklog_sort_by_call();
}

Fl_Button *btn_fsk_name=(Fl_Button *)0;

Fl_Button *btn_fsk_in=(Fl_Button *)0;

Fl_Button *btn_fsk_out=(Fl_Button *)0;

Fl_Button *btn_fsk_sent_nbr=(Fl_Button *)0;

static void cb_btn_fsk_sent_nbr(Fl_Button*, void*) {
  fsklog_sort_by_nbr();
}

Fl_Button *btn_fsk_exchange=(Fl_Button *)0;

Fl_Browser *brwsr_fsklog_entries=(Fl_Browser *)0;

static void cb_brwsr_fsklog_entries(Fl_Browser*, void*) {
  if (!fsklog_editing) fsklog_edit_entry();
}

Fl_Double_Window* new_fsklogbook_dialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(670, 284, gettext("Flrig RTTY Log"));
    w = o; (void)w;
    { FSKlog_menubar = new Fl_Menu_Bar(0, 0, 670, 20);
      { Fl_Menu_Item* o = &menu_FSKlog_menubar[0];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_FSKlog_menubar[1];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_FSKlog_menubar[2];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_FSKlog_menubar[3];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_FSKlog_menubar[4];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_FSKlog_menubar[5];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_FSKlog_menubar[6];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_FSKlog_menubar[8];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_FSKlog_menubar[9];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_FSKlog_menubar[10];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_FSKlog_menubar[11];
        o->label(gettext(o->label()));
      }
      FSKlog_menubar->menu(menu_FSKlog_menubar);
    } // Fl_Menu_Bar* FSKlog_menubar
    { Fl_Group* o = new Fl_Group(2, 22, 668, 29);
      o->box(FL_ENGRAVED_FRAME);
      { txt_fsklog_file = new Fl_Output(75, 26, 590, 22, gettext("Log File:"));
        txt_fsklog_file->callback((Fl_Callback*)cb_txt_fsklog_file);
        //->value(progStatus.fsklogfile_name);
      } // Fl_Output* txt_fsklog_file
      o->end();
    } // Fl_Group* o
    { fsk_grp_qso_data = new Fl_Group(2, 52, 560, 30);
      fsk_grp_qso_data->box(FL_ENGRAVED_BOX);
      { fsk_op_freq = new Fl_Input2(43, 56, 120, 22, gettext("Freq"));
        fsk_op_freq->tooltip(gettext("Frequency"));
        fsk_op_freq->box(FL_DOWN_BOX);
        fsk_op_freq->color(FL_BACKGROUND2_COLOR);
        fsk_op_freq->selection_color(FL_SELECTION_COLOR);
        fsk_op_freq->labeltype(FL_NORMAL_LABEL);
        fsk_op_freq->labelfont(0);
        fsk_op_freq->labelsize(14);
        fsk_op_freq->labelcolor(FL_FOREGROUND_COLOR);
        fsk_op_freq->align(Fl_Align(FL_ALIGN_LEFT));
        fsk_op_freq->when(FL_WHEN_RELEASE);
      } // Fl_Input2* fsk_op_freq
      { btn_fsklog_clear_qso = new Fl_Button(380, 56, 60, 22, gettext("Clear"));
        btn_fsklog_clear_qso->tooltip(gettext("Clear fsklog entries"));
        btn_fsklog_clear_qso->callback((Fl_Callback*)cb_btn_fsklog_clear_qso);
      } // Fl_Button* btn_fsklog_clear_qso
      { btn_fsklog_save_qso = new Fl_Button(440, 56, 60, 22, gettext("Save"));
        btn_fsklog_save_qso->tooltip(gettext("Save QSO data to fsklog file"));
        btn_fsklog_save_qso->callback((Fl_Callback*)cb_btn_fsklog_save_qso);
      } // Fl_Button* btn_fsklog_save_qso
      { btn_fsklog_edit_entry = new Fl_Button(501, 56, 60, 22, gettext("Edit"));
        btn_fsklog_edit_entry->tooltip(gettext("Delete Entry"));
        btn_fsklog_edit_entry->callback((Fl_Callback*)cb_btn_fsklog_edit_entry);
      } // Fl_Button* btn_fsklog_edit_entry
      { btn_fsklog_delete_entry = new Fl_Button(492, 56, 60, 22, gettext("Delete"));
        btn_fsklog_delete_entry->tooltip(gettext("Delete Entry"));
        btn_fsklog_delete_entry->callback((Fl_Callback*)cb_btn_fsklog_delete_entry);
        btn_fsklog_delete_entry->hide();
      } // Fl_Button* btn_fsklog_delete_entry
      { fsk_date = new Fl_Input2(193, 56, 85, 22, gettext("Dt"));
        fsk_date->tooltip(gettext("QSO call\nQuery flfsklog if connected"));
        fsk_date->box(FL_DOWN_BOX);
        fsk_date->color(FL_BACKGROUND2_COLOR);
        fsk_date->selection_color(FL_SELECTION_COLOR);
        fsk_date->labeltype(FL_NORMAL_LABEL);
        fsk_date->labelfont(0);
        fsk_date->labelsize(14);
        fsk_date->labelcolor(FL_FOREGROUND_COLOR);
        fsk_date->align(Fl_Align(FL_ALIGN_LEFT));
        fsk_date->when(FL_WHEN_RELEASE);
      } // Fl_Input2* fsk_date
      { fsk_time = new Fl_Input2(313, 56, 55, 22, gettext("Tm:"));
        fsk_time->box(FL_DOWN_BOX);
        fsk_time->color(FL_BACKGROUND2_COLOR);
        fsk_time->selection_color(FL_SELECTION_COLOR);
        fsk_time->labeltype(FL_NORMAL_LABEL);
        fsk_time->labelfont(0);
        fsk_time->labelsize(14);
        fsk_time->labelcolor(FL_FOREGROUND_COLOR);
        fsk_time->align(Fl_Align(FL_ALIGN_LEFT));
        fsk_time->when(FL_WHEN_RELEASE);
      } // Fl_Input2* fsk_time
      fsk_grp_qso_data->end();
    } // Fl_Group* fsk_grp_qso_data
    { Fl_Group* o = new Fl_Group(565, 52, 103, 62);
      o->box(FL_ENGRAVED_BOX);
      { fsk_rst_out = new Fl_Input2(622, 56, 40, 22, gettext("RSTout"));
        fsk_rst_out->tooltip(gettext("Send RST"));
        fsk_rst_out->box(FL_DOWN_BOX);
        fsk_rst_out->color(FL_BACKGROUND2_COLOR);
        fsk_rst_out->selection_color(FL_SELECTION_COLOR);
        fsk_rst_out->labeltype(FL_NORMAL_LABEL);
        fsk_rst_out->labelfont(0);
        fsk_rst_out->labelsize(14);
        fsk_rst_out->labelcolor(FL_FOREGROUND_COLOR);
        fsk_rst_out->align(Fl_Align(FL_ALIGN_LEFT));
        fsk_rst_out->when(FL_WHEN_RELEASE);
      } // Fl_Input2* fsk_rst_out
      { fsk_rst_in = new Fl_Input2(624, 87, 40, 22, gettext("RST in"));
        fsk_rst_in->tooltip(gettext("Send RST"));
        fsk_rst_in->box(FL_DOWN_BOX);
        fsk_rst_in->color(FL_BACKGROUND2_COLOR);
        fsk_rst_in->selection_color(FL_SELECTION_COLOR);
        fsk_rst_in->labeltype(FL_NORMAL_LABEL);
        fsk_rst_in->labelfont(0);
        fsk_rst_in->labelsize(14);
        fsk_rst_in->labelcolor(FL_FOREGROUND_COLOR);
        fsk_rst_in->align(Fl_Align(FL_ALIGN_LEFT));
        fsk_rst_in->when(FL_WHEN_RELEASE);
      } // Fl_Input2* fsk_rst_in
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(2, 84, 560, 30);
      o->box(FL_ENGRAVED_FRAME);
      { fsk_xchg_in = new Fl_Input2(313, 87, 150, 22, gettext("Xch"));
        fsk_xchg_in->tooltip(gettext("Input exchange"));
        fsk_xchg_in->box(FL_DOWN_BOX);
        fsk_xchg_in->color(FL_BACKGROUND2_COLOR);
        fsk_xchg_in->selection_color(FL_SELECTION_COLOR);
        fsk_xchg_in->labeltype(FL_NORMAL_LABEL);
        fsk_xchg_in->labelfont(0);
        fsk_xchg_in->labelsize(14);
        fsk_xchg_in->labelcolor(FL_FOREGROUND_COLOR);
        fsk_xchg_in->align(Fl_Align(FL_ALIGN_LEFT));
        fsk_xchg_in->when(FL_WHEN_RELEASE);
      } // Fl_Input2* fsk_xchg_in
      { Fl_Counter* o = cntr_fsk_log_nbr = new Fl_Counter(491, 87, 70, 22, gettext("#:"));
        cntr_fsk_log_nbr->tooltip(gettext("QSO number (out)"));
        cntr_fsk_log_nbr->type(1);
        cntr_fsk_log_nbr->step(1);
        cntr_fsk_log_nbr->callback((Fl_Callback*)cb_cntr_fsk_log_nbr);
        cntr_fsk_log_nbr->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.fsk_log_nbr);
      } // Fl_Counter* cntr_fsk_log_nbr
      { fsk_op_name = new Fl_Input2(193, 88, 85, 22, gettext("Nm"));
        fsk_op_name->box(FL_DOWN_BOX);
        fsk_op_name->color(FL_BACKGROUND2_COLOR);
        fsk_op_name->selection_color(FL_SELECTION_COLOR);
        fsk_op_name->labeltype(FL_NORMAL_LABEL);
        fsk_op_name->labelfont(0);
        fsk_op_name->labelsize(14);
        fsk_op_name->labelcolor(FL_FOREGROUND_COLOR);
        fsk_op_name->align(Fl_Align(FL_ALIGN_LEFT));
        fsk_op_name->when(FL_WHEN_RELEASE);
      } // Fl_Input2* fsk_op_name
      { fsk_op_call = new Fl_Input2(43, 88, 120, 22, gettext("Call"));
        fsk_op_call->tooltip(gettext("QSO call\nQuery flfsklog if connected"));
        fsk_op_call->box(FL_DOWN_BOX);
        fsk_op_call->color(FL_BACKGROUND2_COLOR);
        fsk_op_call->selection_color(FL_SELECTION_COLOR);
        fsk_op_call->labeltype(FL_NORMAL_LABEL);
        fsk_op_call->labelfont(0);
        fsk_op_call->labelsize(14);
        fsk_op_call->labelcolor(FL_FOREGROUND_COLOR);
        fsk_op_call->align(Fl_Align(FL_ALIGN_LEFT));
        fsk_op_call->when(FL_WHEN_RELEASE);
      } // Fl_Input2* fsk_op_call
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(2, 113, 674, 170);
      { Fl_Group* o = new Fl_Group(2, 116, 668, 22);
        { btn_fsk_datetime = new Fl_Button(2, 116, 80, 22, gettext("Date"));
          btn_fsk_datetime->box(FL_BORDER_BOX);
          btn_fsk_datetime->color((Fl_Color)51);
          btn_fsk_datetime->callback((Fl_Callback*)cb_btn_fsk_datetime);
        } // Fl_Button* btn_fsk_datetime
        { btn_fsk_time = new Fl_Button(81, 116, 45, 22, gettext("Time"));
          btn_fsk_time->box(FL_BORDER_BOX);
          btn_fsk_time->color((Fl_Color)51);
          btn_fsk_time->callback((Fl_Callback*)cb_btn_fsk_time);
        } // Fl_Button* btn_fsk_time
        { btn_fsk_freq = new Fl_Button(126, 116, 70, 22, gettext("Freq"));
          btn_fsk_freq->box(FL_BORDER_BOX);
          btn_fsk_freq->color((Fl_Color)51);
          btn_fsk_freq->callback((Fl_Callback*)cb_btn_fsk_freq);
        } // Fl_Button* btn_fsk_freq
        { btn_fsk_call = new Fl_Button(196, 116, 75, 22, gettext("Call"));
          btn_fsk_call->box(FL_BORDER_BOX);
          btn_fsk_call->color((Fl_Color)51);
          btn_fsk_call->callback((Fl_Callback*)cb_btn_fsk_call);
        } // Fl_Button* btn_fsk_call
        { btn_fsk_name = new Fl_Button(271, 116, 75, 22, gettext("Name"));
          btn_fsk_name->box(FL_BORDER_BOX);
          btn_fsk_name->color((Fl_Color)51);
        } // Fl_Button* btn_fsk_name
        { btn_fsk_in = new Fl_Button(346, 116, 40, 22, gettext("In"));
          btn_fsk_in->box(FL_BORDER_BOX);
          btn_fsk_in->color((Fl_Color)51);
        } // Fl_Button* btn_fsk_in
        { btn_fsk_out = new Fl_Button(386, 116, 40, 22, gettext("Out"));
          btn_fsk_out->box(FL_BORDER_BOX);
          btn_fsk_out->color((Fl_Color)51);
        } // Fl_Button* btn_fsk_out
        { btn_fsk_sent_nbr = new Fl_Button(426, 116, 55, 22, gettext("Nbr"));
          btn_fsk_sent_nbr->box(FL_BORDER_BOX);
          btn_fsk_sent_nbr->color((Fl_Color)51);
          btn_fsk_sent_nbr->callback((Fl_Callback*)cb_btn_fsk_sent_nbr);
        } // Fl_Button* btn_fsk_sent_nbr
        { btn_fsk_exchange = new Fl_Button(481, 116, 185, 22, gettext("Exchange"));
          btn_fsk_exchange->box(FL_BORDER_BOX);
          btn_fsk_exchange->color((Fl_Color)51);
          Fl_Group::current()->resizable(btn_fsk_exchange);
        } // Fl_Button* btn_fsk_exchange
        o->end();
      } // Fl_Group* o
      { Fl_Browser* o = brwsr_fsklog_entries = new Fl_Browser(2, 140, 666, 141);
        brwsr_fsklog_entries->type(2);
        brwsr_fsklog_entries->selection_color((Fl_Color)230);
        brwsr_fsklog_entries->callback((Fl_Callback*)cb_brwsr_fsklog_entries);
        Fl_Group::current()->resizable(brwsr_fsklog_entries);
        static int widths[]={80,45,70,75,75,40,40,55,0};
        o->column_widths(widths);
        o->column_char('\t');
        o->has_scrollbar(Fl_Browser_::VERTICAL_ALWAYS);
      } // Fl_Browser* brwsr_fsklog_entries
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
