// generated by Fast Light User Interface Designer (fluid) version 1.0404

#include "cwioUI.h"
#include "gettext.h"
#ifndef gettext_noop
#  define gettext_noop(text) text
#endif
#include "config.h"
#include "compat.h"
#include "dialogs.h"
#include "cwio.h"
Fl_Double_Window *cwlog_viewer;
static const char ps[] = "~%&+={}<>@";
static const char szProsigns[] = "~|%|&|+|=|{|}|<|>|@";
Fl_Text_Buffer *cw_sent_buffer;

Fl_Input2 *txt_to_send=(Fl_Input2 *)0;

static void cb_txt_to_send(Fl_Input2*, void*) {
  control_function_keys();
}

Fl_Value_Slider2 *sldr_cwioWPM=(Fl_Value_Slider2 *)0;

static void cb_sldr_cwioWPM(Fl_Value_Slider2* o, void*) {
  progStatus.cwioWPM = (int)o->value();
}

Fl_Button *btn_cwio_config=(Fl_Button *)0;

static void cb_btn_cwio_config(Fl_Button*, void*) {
  open_cwio_config();
}

Fl_Button *btn_cwio_clear=(Fl_Button *)0;

static void cb_btn_cwio_clear(Fl_Button*, void*) {
  if (Fl::event_state(FL_SHIFT))
    cwio_clear_sent_text();
  else
    cwio_clear_text();
}

Fl_Light_Button *btn_cwioKEY=(Fl_Light_Button *)0;

static void cb_btn_cwioKEY(Fl_Light_Button* o, void*) {
  cwio_key (o->value());
  if (o->value()) cwio_process = KEYDOWN;
  else            cwio_process = NONE;
}

Fl_Light_Button *btn_cwioSEND=(Fl_Light_Button *)0;

static void cb_btn_cwioSEND(Fl_Light_Button* o, void*) {
  send_text(o->value());
}

static void cb_btn_msg(Fl_Button*, void*) {
  exec_msg(0);
}

static void cb_btn_msg1(Fl_Button*, void*) {
  exec_msg(1);
}

static void cb_btn_msg2(Fl_Button*, void*) {
  exec_msg(2);
}

static void cb_btn_msg3(Fl_Button*, void*) {
  exec_msg(3);
}

static void cb_btn_msg4(Fl_Button*, void*) {
  exec_msg(4);
}

static void cb_btn_msg5(Fl_Button*, void*) {
  exec_msg(5);
}

static void cb_btn_msg6(Fl_Button*, void*) {
  exec_msg(6);
}

static void cb_btn_msg7(Fl_Button*, void*) {
  exec_msg(7);
}

static void cb_btn_msg8(Fl_Button*, void*) {
  exec_msg(8);
}

static void cb_btn_msg9(Fl_Button*, void*) {
  exec_msg(9);
}

static void cb_btn_msga(Fl_Button*, void*) {
  exec_msg(10);
}

Fl_Button *btn_msg[12]={(Fl_Button *)0};

static void cb_btn_msgb(Fl_Button*, void*) {
  exec_msg(11);
}

Fl_Button *btn_view_cwlog=(Fl_Button *)0;

static void cb_btn_view_cwlog(Fl_Button*, void*) {
  cwlog_view();
}

Fl_Text_Display *cw_sent_text=(Fl_Text_Display *)0;

Fl_Double_Window* new_cwio_dialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(670, 203, gettext("CW keying"));
    w = o; (void)w;
    { txt_to_send = new Fl_Input2(2, 104, 666, 40);
      txt_to_send->type(4);
      txt_to_send->box(FL_DOWN_BOX);
      txt_to_send->color(FL_SELECTION_COLOR);
      txt_to_send->selection_color(FL_SELECTION_COLOR);
      txt_to_send->labeltype(FL_NORMAL_LABEL);
      txt_to_send->labelfont(0);
      txt_to_send->labelsize(14);
      txt_to_send->labelcolor(FL_FOREGROUND_COLOR);
      txt_to_send->textfont(13);
      txt_to_send->textsize(16);
      txt_to_send->callback((Fl_Callback*)cb_txt_to_send);
      txt_to_send->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      txt_to_send->when(FL_WHEN_CHANGED);
    } // Fl_Input2* txt_to_send
    { Fl_Group* o = new Fl_Group(0, 147, 670, 56);
      { Fl_Value_Slider2* o = sldr_cwioWPM = new Fl_Value_Slider2(4, 149, 240, 20, gettext("WPM"));
        sldr_cwioWPM->tooltip(gettext("My transmit CW WPM"));
        sldr_cwioWPM->type(5);
        sldr_cwioWPM->box(FL_DOWN_BOX);
        sldr_cwioWPM->color(FL_BACKGROUND_COLOR);
        sldr_cwioWPM->selection_color(FL_BACKGROUND_COLOR);
        sldr_cwioWPM->labeltype(FL_NORMAL_LABEL);
        sldr_cwioWPM->labelfont(0);
        sldr_cwioWPM->labelsize(14);
        sldr_cwioWPM->labelcolor(FL_FOREGROUND_COLOR);
        sldr_cwioWPM->minimum(5);
        sldr_cwioWPM->maximum(100);
        sldr_cwioWPM->step(1);
        sldr_cwioWPM->value(20);
        sldr_cwioWPM->textsize(14);
        sldr_cwioWPM->callback((Fl_Callback*)cb_sldr_cwioWPM);
        sldr_cwioWPM->align(Fl_Align(FL_ALIGN_RIGHT));
        sldr_cwioWPM->when(FL_WHEN_CHANGED);
        o->value(progStatus.cwioWPM);
      } // Fl_Value_Slider2* sldr_cwioWPM
      { btn_cwio_config = new Fl_Button(374, 148, 60, 22, gettext("Config"));
        btn_cwio_config->tooltip(gettext("Configure cwio"));
        btn_cwio_config->callback((Fl_Callback*)cb_btn_cwio_config);
      } // Fl_Button* btn_cwio_config
      { btn_cwio_clear = new Fl_Button(439, 148, 60, 22, gettext("Clear"));
        btn_cwio_clear->tooltip(gettext("Clear PENDING text\nShift - Clear SENT text"));
        btn_cwio_clear->callback((Fl_Callback*)cb_btn_cwio_clear);
      } // Fl_Button* btn_cwio_clear
      { btn_cwioKEY = new Fl_Light_Button(503, 148, 50, 22, gettext("KEY"));
        btn_cwioKEY->tooltip(gettext("Key Down / Up"));
        btn_cwioKEY->callback((Fl_Callback*)cb_btn_cwioKEY);
      } // Fl_Light_Button* btn_cwioKEY
      { btn_cwioSEND = new Fl_Light_Button(557, 148, 105, 22, gettext("Send/Pause"));
        btn_cwioSEND->tooltip(gettext("Send / Pause sending characters"));
        btn_cwioSEND->callback((Fl_Callback*)cb_btn_cwioSEND);
      } // Fl_Light_Button* btn_cwioSEND
      { Fl_Group* o = new Fl_Group(2, 173, 220, 30);
        o->box(FL_ENGRAVED_BOX);
        { btn_msg[0] = new Fl_Button(5, 177, 50, 22, gettext("F 1"));
          btn_msg[0]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[0]->callback((Fl_Callback*)cb_btn_msg);
        } // Fl_Button* btn_msg[0]
        { btn_msg[1] = new Fl_Button(59, 177, 50, 22, gettext("F 2"));
          btn_msg[1]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[1]->callback((Fl_Callback*)cb_btn_msg1);
        } // Fl_Button* btn_msg[1]
        { btn_msg[2] = new Fl_Button(113, 177, 50, 22, gettext("F 3"));
          btn_msg[2]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[2]->callback((Fl_Callback*)cb_btn_msg2);
        } // Fl_Button* btn_msg[2]
        { btn_msg[3] = new Fl_Button(168, 177, 50, 22, gettext("F 4"));
          btn_msg[3]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[3]->callback((Fl_Callback*)cb_btn_msg3);
        } // Fl_Button* btn_msg[3]
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(225, 173, 220, 30);
        o->box(FL_ENGRAVED_BOX);
        { btn_msg[4] = new Fl_Button(229, 177, 50, 22, gettext("F 5"));
          btn_msg[4]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[4]->callback((Fl_Callback*)cb_btn_msg4);
        } // Fl_Button* btn_msg[4]
        { btn_msg[5] = new Fl_Button(283, 177, 50, 22, gettext("F 6"));
          btn_msg[5]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[5]->callback((Fl_Callback*)cb_btn_msg5);
        } // Fl_Button* btn_msg[5]
        { btn_msg[6] = new Fl_Button(337, 177, 50, 22, gettext("F 7"));
          btn_msg[6]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[6]->callback((Fl_Callback*)cb_btn_msg6);
        } // Fl_Button* btn_msg[6]
        { btn_msg[7] = new Fl_Button(391, 177, 50, 22, gettext("F 8"));
          btn_msg[7]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[7]->callback((Fl_Callback*)cb_btn_msg7);
        } // Fl_Button* btn_msg[7]
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(448, 173, 220, 30);
        o->box(FL_ENGRAVED_BOX);
        { btn_msg[8] = new Fl_Button(451, 177, 50, 22, gettext("F 9"));
          btn_msg[8]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[8]->callback((Fl_Callback*)cb_btn_msg8);
        } // Fl_Button* btn_msg[8]
        { btn_msg[9] = new Fl_Button(505, 177, 50, 22, gettext("F 10"));
          btn_msg[9]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[9]->callback((Fl_Callback*)cb_btn_msg9);
        } // Fl_Button* btn_msg[9]
        { btn_msg[10] = new Fl_Button(559, 177, 50, 22, gettext("F 11"));
          btn_msg[10]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[10]->callback((Fl_Callback*)cb_btn_msga);
        } // Fl_Button* btn_msg[10]
        { btn_msg[11] = new Fl_Button(614, 177, 50, 22, gettext("F 12"));
          btn_msg[11]->tooltip(gettext("Action - Function Key Left click\nEdit - Control left click"));
          btn_msg[11]->callback((Fl_Callback*)cb_btn_msgb);
        } // Fl_Button* btn_msg[11]
        o->end();
      } // Fl_Group* o
      { btn_view_cwlog = new Fl_Button(294, 148, 75, 22, gettext("View Log"));
        btn_view_cwlog->tooltip(gettext("View cwlogbook"));
        btn_view_cwlog->callback((Fl_Callback*)cb_btn_view_cwlog);
      } // Fl_Button* btn_view_cwlog
      o->end();
    } // Fl_Group* o
    { Fl_Text_Display* o = cw_sent_text = new Fl_Text_Display(1, 2, 666, 100);
      cw_sent_text->color((Fl_Color)20);
      cw_sent_text->textfont(13);
      cw_sent_text->textsize(16);
      cw_sent_text->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
      Fl_Group::current()->resizable(cw_sent_text);
      cw_sent_buffer = new Fl_Text_Buffer();
      o->buffer(cw_sent_buffer);
    } // Fl_Text_Display* cw_sent_text
    o->end();
  } // Fl_Double_Window* o
  return w;
}

static void cb_edit_label(Fl_Input2*, void*) {
  label_cb(1);
}

static void cb_edit_msg(Fl_Input2*, void*) {
  msg_cb(1);
}

static void cb_edit_label1(Fl_Input2*, void*) {
  label_cb(2);
}

static void cb_edit_msg1(Fl_Input2*, void*) {
  msg_cb(2);
}

static void cb_edit_label2(Fl_Input2*, void*) {
  label_cb(3);
}

static void cb_edit_msg2(Fl_Input2*, void*) {
  msg_cb(3);
}

static void cb_edit_label3(Fl_Input2*, void*) {
  label_cb(4);
}

static void cb_edit_msg3(Fl_Input2*, void*) {
  msg_cb(4);
}

static void cb_edit_label4(Fl_Input2*, void*) {
  label_cb(5);
}

static void cb_edit_msg4(Fl_Input2*, void*) {
  msg_cb(5);
}

static void cb_edit_label5(Fl_Input2*, void*) {
  label_cb(6);
}

static void cb_edit_msg5(Fl_Input2*, void*) {
  msg_cb(6);
}

static void cb_edit_label6(Fl_Input2*, void*) {
  label_cb(7);
}

static void cb_edit_msg6(Fl_Input2*, void*) {
  msg_cb(7);
}

static void cb_edit_label7(Fl_Input2*, void*) {
  label_cb(8);
}

static void cb_edit_msg7(Fl_Input2*, void*) {
  msg_cb(8);
}

static void cb_edit_label8(Fl_Input2*, void*) {
  label_cb(9);
}

static void cb_edit_msg8(Fl_Input2*, void*) {
  msg_cb(9);
}

static void cb_edit_label9(Fl_Input2*, void*) {
  label_cb(10);
}

static void cb_edit_msg9(Fl_Input2*, void*) {
  msg_cb(10);
}

static void cb_edit_labela(Fl_Input2*, void*) {
  label_cb(11);
}

static void cb_edit_msga(Fl_Input2*, void*) {
  msg_cb(11);
}

Fl_Input2 *edit_label[12]={(Fl_Input2 *)0};

static void cb_edit_labelb(Fl_Input2*, void*) {
  label_cb(12);
}

Fl_Input2 *edit_msg[12]={(Fl_Input2 *)0};

static void cb_edit_msgb(Fl_Input2*, void*) {
  msg_cb(12);
}

Fl_ListBox *listbox_BT=(Fl_ListBox *)0;

static void cb_listbox_BT(Fl_ListBox* o, void*) {
  int c = o->index();
  progStatus.BT[0] = ps[c];
  morse->init();
}

Fl_ListBox *listbox_AA=(Fl_ListBox *)0;

static void cb_listbox_AA(Fl_ListBox* o, void*) {
  int c = o->index();
  progStatus.AA[0] = ps[c];
  morse->init();
}

Fl_ListBox *listbox_AS=(Fl_ListBox *)0;

static void cb_listbox_AS(Fl_ListBox* o, void*) {
  int c = o->index();
  progStatus.AS[0] = ps[c];
  morse->init();
}

Fl_ListBox *listbox_AR=(Fl_ListBox *)0;

static void cb_listbox_AR(Fl_ListBox* o, void*) {
  int c = o->index();
  progStatus.AR[0] = ps[c];
  morse->init();
}

Fl_ListBox *listbox_SK=(Fl_ListBox *)0;

static void cb_listbox_SK(Fl_ListBox* o, void*) {
  int c = o->index();
  progStatus.SK[0] = ps[c];
  morse->init();
}

Fl_ListBox *listbox_KN=(Fl_ListBox *)0;

static void cb_listbox_KN(Fl_ListBox* o, void*) {
  int c = o->index();
  progStatus.KN[0] = ps[c];
  morse->init();
}

Fl_ListBox *listbox_INT=(Fl_ListBox *)0;

static void cb_listbox_INT(Fl_ListBox* o, void*) {
  int c = o->index();
  progStatus.INT[0] = ps[c];
  morse->init();
}

Fl_ListBox *listbox_HM=(Fl_ListBox *)0;

static void cb_listbox_HM(Fl_ListBox* o, void*) {
  int c = o->index();
  progStatus.HM[0] = ps[c];
  morse->init();
}

Fl_ListBox *listbox_VE=(Fl_ListBox *)0;

static void cb_listbox_VE(Fl_ListBox* o, void*) {
  int c = o->index();
  progStatus.VE[0] = ps[c];
  morse->init();
}

Fl_Button *btn_start_xmt=(Fl_Button *)0;

Fl_Button *btn_end_xmt=(Fl_Button *)0;

Fl_Button *btn_append_call=(Fl_Button *)0;

Fl_Button *btn_append_name=(Fl_Button *)0;

Fl_Button *btn_append_rst=(Fl_Button *)0;

Fl_Button *btn_cancel_edit=(Fl_Button *)0;

static void cb_btn_cancel_edit(Fl_Button*, void*) {
  cancel_edit();
}

Fl_Button *btn_apply_edit=(Fl_Button *)0;

static void cb_btn_apply_edit(Fl_Button*, void*) {
  apply_edit();
}

Fl_Button *btn_done_edit=(Fl_Button *)0;

static void cb_btn_done_edit(Fl_Button*, void*) {
  done_edit();
}

Fl_Button *btn_append_contest_nbr=(Fl_Button *)0;

Fl_Button *btn_append_decr=(Fl_Button *)0;

Fl_Button *btn_append_incr=(Fl_Button *)0;

Fl_Double_Window* new_message_editor() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(670, 382, gettext("Message Editor"));
    w = o; (void)w;
    { Fl_Tabs* o = new Fl_Tabs(0, 0, 565, 345);
      o->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
      { Fl_Group* o = new Fl_Group(0, 25, 565, 320, gettext("F1-F4"));
        o->hide();
        { new Fl_Box(22, 30, 84, 20, gettext("Label"));
        } // Fl_Box* o
        { new Fl_Box(211, 30, 223, 20, gettext("Message Text"));
        } // Fl_Box* o
        { edit_label[0] = new Fl_Input2(5, 74, 80, 22, gettext("F1"));
          edit_label[0]->box(FL_DOWN_BOX);
          edit_label[0]->color(FL_BACKGROUND2_COLOR);
          edit_label[0]->selection_color(FL_SELECTION_COLOR);
          edit_label[0]->labeltype(FL_NORMAL_LABEL);
          edit_label[0]->labelfont(0);
          edit_label[0]->labelsize(14);
          edit_label[0]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[0]->callback((Fl_Callback*)cb_edit_label);
          edit_label[0]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[0]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[0]
        { edit_msg[0] = new Fl_Input2(90, 55, 470, 65);
          edit_msg[0]->type(4);
          edit_msg[0]->box(FL_DOWN_BOX);
          edit_msg[0]->color(FL_BACKGROUND2_COLOR);
          edit_msg[0]->selection_color(FL_SELECTION_COLOR);
          edit_msg[0]->labeltype(FL_NORMAL_LABEL);
          edit_msg[0]->labelfont(0);
          edit_msg[0]->labelsize(14);
          edit_msg[0]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[0]->callback((Fl_Callback*)cb_edit_msg);
          edit_msg[0]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[0]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[0]
        { edit_label[1] = new Fl_Input2(5, 144, 80, 22, gettext("F2"));
          edit_label[1]->box(FL_DOWN_BOX);
          edit_label[1]->color(FL_BACKGROUND2_COLOR);
          edit_label[1]->selection_color(FL_SELECTION_COLOR);
          edit_label[1]->labeltype(FL_NORMAL_LABEL);
          edit_label[1]->labelfont(0);
          edit_label[1]->labelsize(14);
          edit_label[1]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[1]->callback((Fl_Callback*)cb_edit_label1);
          edit_label[1]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[1]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[1]
        { edit_msg[1] = new Fl_Input2(90, 125, 470, 65);
          edit_msg[1]->type(4);
          edit_msg[1]->box(FL_DOWN_BOX);
          edit_msg[1]->color(FL_BACKGROUND2_COLOR);
          edit_msg[1]->selection_color(FL_SELECTION_COLOR);
          edit_msg[1]->labeltype(FL_NORMAL_LABEL);
          edit_msg[1]->labelfont(0);
          edit_msg[1]->labelsize(14);
          edit_msg[1]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[1]->callback((Fl_Callback*)cb_edit_msg1);
          edit_msg[1]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[1]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[1]
        { edit_label[2] = new Fl_Input2(5, 214, 80, 22, gettext("F3"));
          edit_label[2]->box(FL_DOWN_BOX);
          edit_label[2]->color(FL_BACKGROUND2_COLOR);
          edit_label[2]->selection_color(FL_SELECTION_COLOR);
          edit_label[2]->labeltype(FL_NORMAL_LABEL);
          edit_label[2]->labelfont(0);
          edit_label[2]->labelsize(14);
          edit_label[2]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[2]->callback((Fl_Callback*)cb_edit_label2);
          edit_label[2]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[2]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[2]
        { edit_msg[2] = new Fl_Input2(90, 195, 470, 65);
          edit_msg[2]->type(4);
          edit_msg[2]->box(FL_DOWN_BOX);
          edit_msg[2]->color(FL_BACKGROUND2_COLOR);
          edit_msg[2]->selection_color(FL_SELECTION_COLOR);
          edit_msg[2]->labeltype(FL_NORMAL_LABEL);
          edit_msg[2]->labelfont(0);
          edit_msg[2]->labelsize(14);
          edit_msg[2]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[2]->callback((Fl_Callback*)cb_edit_msg2);
          edit_msg[2]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[2]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[2]
        { edit_label[3] = new Fl_Input2(5, 284, 80, 22, gettext("F4"));
          edit_label[3]->box(FL_DOWN_BOX);
          edit_label[3]->color(FL_BACKGROUND2_COLOR);
          edit_label[3]->selection_color(FL_SELECTION_COLOR);
          edit_label[3]->labeltype(FL_NORMAL_LABEL);
          edit_label[3]->labelfont(0);
          edit_label[3]->labelsize(14);
          edit_label[3]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[3]->callback((Fl_Callback*)cb_edit_label3);
          edit_label[3]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[3]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[3]
        { edit_msg[3] = new Fl_Input2(90, 265, 470, 65);
          edit_msg[3]->type(4);
          edit_msg[3]->box(FL_DOWN_BOX);
          edit_msg[3]->color(FL_BACKGROUND2_COLOR);
          edit_msg[3]->selection_color(FL_SELECTION_COLOR);
          edit_msg[3]->labeltype(FL_NORMAL_LABEL);
          edit_msg[3]->labelfont(0);
          edit_msg[3]->labelsize(14);
          edit_msg[3]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[3]->callback((Fl_Callback*)cb_edit_msg3);
          edit_msg[3]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[3]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[3]
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 25, 565, 320, gettext("F5-F8"));
        o->hide();
        { new Fl_Box(22, 30, 84, 20, gettext("Label"));
        } // Fl_Box* o
        { new Fl_Box(211, 30, 223, 20, gettext("Message Text"));
        } // Fl_Box* o
        { edit_label[4] = new Fl_Input2(5, 74, 80, 22, gettext("F5"));
          edit_label[4]->box(FL_DOWN_BOX);
          edit_label[4]->color(FL_BACKGROUND2_COLOR);
          edit_label[4]->selection_color(FL_SELECTION_COLOR);
          edit_label[4]->labeltype(FL_NORMAL_LABEL);
          edit_label[4]->labelfont(0);
          edit_label[4]->labelsize(14);
          edit_label[4]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[4]->callback((Fl_Callback*)cb_edit_label4);
          edit_label[4]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[4]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[4]
        { edit_msg[4] = new Fl_Input2(90, 55, 470, 65);
          edit_msg[4]->type(4);
          edit_msg[4]->box(FL_DOWN_BOX);
          edit_msg[4]->color(FL_BACKGROUND2_COLOR);
          edit_msg[4]->selection_color(FL_SELECTION_COLOR);
          edit_msg[4]->labeltype(FL_NORMAL_LABEL);
          edit_msg[4]->labelfont(0);
          edit_msg[4]->labelsize(14);
          edit_msg[4]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[4]->callback((Fl_Callback*)cb_edit_msg4);
          edit_msg[4]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[4]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[4]
        { edit_label[5] = new Fl_Input2(5, 144, 80, 22, gettext("F6"));
          edit_label[5]->box(FL_DOWN_BOX);
          edit_label[5]->color(FL_BACKGROUND2_COLOR);
          edit_label[5]->selection_color(FL_SELECTION_COLOR);
          edit_label[5]->labeltype(FL_NORMAL_LABEL);
          edit_label[5]->labelfont(0);
          edit_label[5]->labelsize(14);
          edit_label[5]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[5]->callback((Fl_Callback*)cb_edit_label5);
          edit_label[5]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[5]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[5]
        { edit_msg[5] = new Fl_Input2(90, 125, 470, 65);
          edit_msg[5]->type(4);
          edit_msg[5]->box(FL_DOWN_BOX);
          edit_msg[5]->color(FL_BACKGROUND2_COLOR);
          edit_msg[5]->selection_color(FL_SELECTION_COLOR);
          edit_msg[5]->labeltype(FL_NORMAL_LABEL);
          edit_msg[5]->labelfont(0);
          edit_msg[5]->labelsize(14);
          edit_msg[5]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[5]->callback((Fl_Callback*)cb_edit_msg5);
          edit_msg[5]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[5]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[5]
        { edit_label[6] = new Fl_Input2(5, 214, 80, 22, gettext("F7"));
          edit_label[6]->box(FL_DOWN_BOX);
          edit_label[6]->color(FL_BACKGROUND2_COLOR);
          edit_label[6]->selection_color(FL_SELECTION_COLOR);
          edit_label[6]->labeltype(FL_NORMAL_LABEL);
          edit_label[6]->labelfont(0);
          edit_label[6]->labelsize(14);
          edit_label[6]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[6]->callback((Fl_Callback*)cb_edit_label6);
          edit_label[6]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[6]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[6]
        { edit_msg[6] = new Fl_Input2(90, 195, 470, 65);
          edit_msg[6]->type(4);
          edit_msg[6]->box(FL_DOWN_BOX);
          edit_msg[6]->color(FL_BACKGROUND2_COLOR);
          edit_msg[6]->selection_color(FL_SELECTION_COLOR);
          edit_msg[6]->labeltype(FL_NORMAL_LABEL);
          edit_msg[6]->labelfont(0);
          edit_msg[6]->labelsize(14);
          edit_msg[6]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[6]->callback((Fl_Callback*)cb_edit_msg6);
          edit_msg[6]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[6]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[6]
        { edit_label[7] = new Fl_Input2(5, 284, 80, 22, gettext("F8"));
          edit_label[7]->box(FL_DOWN_BOX);
          edit_label[7]->color(FL_BACKGROUND2_COLOR);
          edit_label[7]->selection_color(FL_SELECTION_COLOR);
          edit_label[7]->labeltype(FL_NORMAL_LABEL);
          edit_label[7]->labelfont(0);
          edit_label[7]->labelsize(14);
          edit_label[7]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[7]->callback((Fl_Callback*)cb_edit_label7);
          edit_label[7]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[7]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[7]
        { edit_msg[7] = new Fl_Input2(90, 265, 470, 65);
          edit_msg[7]->type(4);
          edit_msg[7]->box(FL_DOWN_BOX);
          edit_msg[7]->color(FL_BACKGROUND2_COLOR);
          edit_msg[7]->selection_color(FL_SELECTION_COLOR);
          edit_msg[7]->labeltype(FL_NORMAL_LABEL);
          edit_msg[7]->labelfont(0);
          edit_msg[7]->labelsize(14);
          edit_msg[7]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[7]->callback((Fl_Callback*)cb_edit_msg7);
          edit_msg[7]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[7]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[7]
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(0, 25, 565, 320, gettext("F9-F12"));
        { new Fl_Box(22, 30, 84, 20, gettext("Label"));
        } // Fl_Box* o
        { new Fl_Box(211, 30, 223, 20, gettext("Message Text"));
        } // Fl_Box* o
        { edit_label[8] = new Fl_Input2(5, 73, 80, 22, gettext("F9"));
          edit_label[8]->box(FL_DOWN_BOX);
          edit_label[8]->color(FL_BACKGROUND2_COLOR);
          edit_label[8]->selection_color(FL_SELECTION_COLOR);
          edit_label[8]->labeltype(FL_NORMAL_LABEL);
          edit_label[8]->labelfont(0);
          edit_label[8]->labelsize(14);
          edit_label[8]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[8]->callback((Fl_Callback*)cb_edit_label8);
          edit_label[8]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[8]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[8]
        { edit_msg[8] = new Fl_Input2(90, 55, 470, 65);
          edit_msg[8]->type(4);
          edit_msg[8]->box(FL_DOWN_BOX);
          edit_msg[8]->color(FL_BACKGROUND2_COLOR);
          edit_msg[8]->selection_color(FL_SELECTION_COLOR);
          edit_msg[8]->labeltype(FL_NORMAL_LABEL);
          edit_msg[8]->labelfont(0);
          edit_msg[8]->labelsize(14);
          edit_msg[8]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[8]->callback((Fl_Callback*)cb_edit_msg8);
          edit_msg[8]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[8]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[8]
        { edit_label[9] = new Fl_Input2(5, 143, 80, 22, gettext("F10"));
          edit_label[9]->box(FL_DOWN_BOX);
          edit_label[9]->color(FL_BACKGROUND2_COLOR);
          edit_label[9]->selection_color(FL_SELECTION_COLOR);
          edit_label[9]->labeltype(FL_NORMAL_LABEL);
          edit_label[9]->labelfont(0);
          edit_label[9]->labelsize(14);
          edit_label[9]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[9]->callback((Fl_Callback*)cb_edit_label9);
          edit_label[9]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[9]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[9]
        { edit_msg[9] = new Fl_Input2(90, 125, 470, 65);
          edit_msg[9]->type(4);
          edit_msg[9]->box(FL_DOWN_BOX);
          edit_msg[9]->color(FL_BACKGROUND2_COLOR);
          edit_msg[9]->selection_color(FL_SELECTION_COLOR);
          edit_msg[9]->labeltype(FL_NORMAL_LABEL);
          edit_msg[9]->labelfont(0);
          edit_msg[9]->labelsize(14);
          edit_msg[9]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[9]->callback((Fl_Callback*)cb_edit_msg9);
          edit_msg[9]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[9]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[9]
        { edit_label[10] = new Fl_Input2(5, 213, 80, 22, gettext("F11"));
          edit_label[10]->box(FL_DOWN_BOX);
          edit_label[10]->color(FL_BACKGROUND2_COLOR);
          edit_label[10]->selection_color(FL_SELECTION_COLOR);
          edit_label[10]->labeltype(FL_NORMAL_LABEL);
          edit_label[10]->labelfont(0);
          edit_label[10]->labelsize(14);
          edit_label[10]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[10]->callback((Fl_Callback*)cb_edit_labela);
          edit_label[10]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[10]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[10]
        { edit_msg[10] = new Fl_Input2(90, 195, 470, 65);
          edit_msg[10]->type(4);
          edit_msg[10]->box(FL_DOWN_BOX);
          edit_msg[10]->color(FL_BACKGROUND2_COLOR);
          edit_msg[10]->selection_color(FL_SELECTION_COLOR);
          edit_msg[10]->labeltype(FL_NORMAL_LABEL);
          edit_msg[10]->labelfont(0);
          edit_msg[10]->labelsize(14);
          edit_msg[10]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[10]->callback((Fl_Callback*)cb_edit_msga);
          edit_msg[10]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[10]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[10]
        { edit_label[11] = new Fl_Input2(5, 283, 80, 22, gettext("F12"));
          edit_label[11]->box(FL_DOWN_BOX);
          edit_label[11]->color(FL_BACKGROUND2_COLOR);
          edit_label[11]->selection_color(FL_SELECTION_COLOR);
          edit_label[11]->labeltype(FL_NORMAL_LABEL);
          edit_label[11]->labelfont(0);
          edit_label[11]->labelsize(14);
          edit_label[11]->labelcolor(FL_FOREGROUND_COLOR);
          edit_label[11]->callback((Fl_Callback*)cb_edit_labelb);
          edit_label[11]->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          edit_label[11]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_label[11]
        { edit_msg[11] = new Fl_Input2(90, 265, 470, 65);
          edit_msg[11]->type(4);
          edit_msg[11]->box(FL_DOWN_BOX);
          edit_msg[11]->color(FL_BACKGROUND2_COLOR);
          edit_msg[11]->selection_color(FL_SELECTION_COLOR);
          edit_msg[11]->labeltype(FL_NORMAL_LABEL);
          edit_msg[11]->labelfont(0);
          edit_msg[11]->labelsize(14);
          edit_msg[11]->labelcolor(FL_FOREGROUND_COLOR);
          edit_msg[11]->callback((Fl_Callback*)cb_edit_msgb);
          edit_msg[11]->align(Fl_Align(FL_ALIGN_LEFT));
          edit_msg[11]->when(FL_WHEN_RELEASE);
        } // Fl_Input2* edit_msg[11]
        o->end();
      } // Fl_Group* o
      o->end();
    } // Fl_Tabs* o
    { Fl_Group* o = new Fl_Group(567, 0, 101, 224);
      o->box(FL_ENGRAVED_FRAME);
      { Fl_ListBox* o = listbox_BT = new Fl_ListBox(600, 6, 60, 22, gettext("BT"));
        listbox_BT->box(FL_DOWN_BOX);
        listbox_BT->color(FL_BACKGROUND2_COLOR);
        listbox_BT->selection_color(FL_BACKGROUND_COLOR);
        listbox_BT->labeltype(FL_NORMAL_LABEL);
        listbox_BT->labelfont(0);
        listbox_BT->labelsize(14);
        listbox_BT->labelcolor(FL_FOREGROUND_COLOR);
        listbox_BT->callback((Fl_Callback*)cb_listbox_BT);
        listbox_BT->align(Fl_Align(FL_ALIGN_LEFT));
        listbox_BT->when(FL_WHEN_RELEASE);
        o->add(szProsigns);
        o->value(progStatus.BT.c_str()); o->labelsize(FL_NORMAL_SIZE);
        listbox_BT->end();
      } // Fl_ListBox* listbox_BT
      { Fl_ListBox* o = listbox_AA = new Fl_ListBox(600, 30, 60, 22, gettext("AA"));
        listbox_AA->box(FL_DOWN_BOX);
        listbox_AA->color(FL_BACKGROUND2_COLOR);
        listbox_AA->selection_color(FL_BACKGROUND_COLOR);
        listbox_AA->labeltype(FL_NORMAL_LABEL);
        listbox_AA->labelfont(0);
        listbox_AA->labelsize(14);
        listbox_AA->labelcolor(FL_FOREGROUND_COLOR);
        listbox_AA->callback((Fl_Callback*)cb_listbox_AA);
        listbox_AA->align(Fl_Align(FL_ALIGN_LEFT));
        listbox_AA->when(FL_WHEN_RELEASE);
        o->add(szProsigns);
        o->value(progStatus.AA.c_str()); o->labelsize(FL_NORMAL_SIZE);
        listbox_AA->end();
      } // Fl_ListBox* listbox_AA
      { Fl_ListBox* o = listbox_AS = new Fl_ListBox(600, 54, 60, 22, gettext("AS"));
        listbox_AS->box(FL_DOWN_BOX);
        listbox_AS->color(FL_BACKGROUND2_COLOR);
        listbox_AS->selection_color(FL_BACKGROUND_COLOR);
        listbox_AS->labeltype(FL_NORMAL_LABEL);
        listbox_AS->labelfont(0);
        listbox_AS->labelsize(14);
        listbox_AS->labelcolor(FL_FOREGROUND_COLOR);
        listbox_AS->callback((Fl_Callback*)cb_listbox_AS);
        listbox_AS->align(Fl_Align(FL_ALIGN_LEFT));
        listbox_AS->when(FL_WHEN_RELEASE);
        o->add(szProsigns);
        o->value(progStatus.AS.c_str()); o->labelsize(FL_NORMAL_SIZE);
        listbox_AS->end();
      } // Fl_ListBox* listbox_AS
      { Fl_ListBox* o = listbox_AR = new Fl_ListBox(600, 78, 60, 22, gettext("AR"));
        listbox_AR->box(FL_DOWN_BOX);
        listbox_AR->color(FL_BACKGROUND2_COLOR);
        listbox_AR->selection_color(FL_BACKGROUND_COLOR);
        listbox_AR->labeltype(FL_NORMAL_LABEL);
        listbox_AR->labelfont(0);
        listbox_AR->labelsize(14);
        listbox_AR->labelcolor(FL_FOREGROUND_COLOR);
        listbox_AR->callback((Fl_Callback*)cb_listbox_AR);
        listbox_AR->align(Fl_Align(FL_ALIGN_LEFT));
        listbox_AR->when(FL_WHEN_RELEASE);
        o->add(szProsigns);
        o->value(progStatus.AR.c_str()); o->labelsize(FL_NORMAL_SIZE);
        listbox_AR->end();
      } // Fl_ListBox* listbox_AR
      { Fl_ListBox* o = listbox_SK = new Fl_ListBox(600, 102, 60, 22, gettext("SK"));
        listbox_SK->box(FL_DOWN_BOX);
        listbox_SK->color(FL_BACKGROUND2_COLOR);
        listbox_SK->selection_color(FL_BACKGROUND_COLOR);
        listbox_SK->labeltype(FL_NORMAL_LABEL);
        listbox_SK->labelfont(0);
        listbox_SK->labelsize(14);
        listbox_SK->labelcolor(FL_FOREGROUND_COLOR);
        listbox_SK->callback((Fl_Callback*)cb_listbox_SK);
        listbox_SK->align(Fl_Align(FL_ALIGN_LEFT));
        listbox_SK->when(FL_WHEN_RELEASE);
        o->add(szProsigns);
        o->value(progStatus.SK.c_str()); o->labelsize(FL_NORMAL_SIZE);
        listbox_SK->end();
      } // Fl_ListBox* listbox_SK
      { Fl_ListBox* o = listbox_KN = new Fl_ListBox(600, 126, 60, 22, gettext("KN"));
        listbox_KN->box(FL_DOWN_BOX);
        listbox_KN->color(FL_BACKGROUND2_COLOR);
        listbox_KN->selection_color(FL_BACKGROUND_COLOR);
        listbox_KN->labeltype(FL_NORMAL_LABEL);
        listbox_KN->labelfont(0);
        listbox_KN->labelsize(14);
        listbox_KN->labelcolor(FL_FOREGROUND_COLOR);
        listbox_KN->callback((Fl_Callback*)cb_listbox_KN);
        listbox_KN->align(Fl_Align(FL_ALIGN_LEFT));
        listbox_KN->when(FL_WHEN_RELEASE);
        o->add(szProsigns);
        o->value(progStatus.KN.c_str()); o->labelsize(FL_NORMAL_SIZE);
        listbox_KN->end();
      } // Fl_ListBox* listbox_KN
      { Fl_ListBox* o = listbox_INT = new Fl_ListBox(600, 150, 60, 22, gettext("INT"));
        listbox_INT->box(FL_DOWN_BOX);
        listbox_INT->color(FL_BACKGROUND2_COLOR);
        listbox_INT->selection_color(FL_BACKGROUND_COLOR);
        listbox_INT->labeltype(FL_NORMAL_LABEL);
        listbox_INT->labelfont(0);
        listbox_INT->labelsize(14);
        listbox_INT->labelcolor(FL_FOREGROUND_COLOR);
        listbox_INT->callback((Fl_Callback*)cb_listbox_INT);
        listbox_INT->align(Fl_Align(FL_ALIGN_LEFT));
        listbox_INT->when(FL_WHEN_RELEASE);
        o->add(szProsigns);
        o->value(progStatus.INT.c_str()); o->labelsize(FL_NORMAL_SIZE);
        listbox_INT->end();
      } // Fl_ListBox* listbox_INT
      { Fl_ListBox* o = listbox_HM = new Fl_ListBox(600, 174, 60, 22, gettext("HM"));
        listbox_HM->box(FL_DOWN_BOX);
        listbox_HM->color(FL_BACKGROUND2_COLOR);
        listbox_HM->selection_color(FL_BACKGROUND_COLOR);
        listbox_HM->labeltype(FL_NORMAL_LABEL);
        listbox_HM->labelfont(0);
        listbox_HM->labelsize(14);
        listbox_HM->labelcolor(FL_FOREGROUND_COLOR);
        listbox_HM->callback((Fl_Callback*)cb_listbox_HM);
        listbox_HM->align(Fl_Align(FL_ALIGN_LEFT));
        listbox_HM->when(FL_WHEN_RELEASE);
        o->add(szProsigns);
        o->value(progStatus.HM.c_str()); o->labelsize(FL_NORMAL_SIZE);
        listbox_HM->end();
      } // Fl_ListBox* listbox_HM
      { Fl_ListBox* o = listbox_VE = new Fl_ListBox(600, 199, 60, 22, gettext("VE"));
        listbox_VE->box(FL_DOWN_BOX);
        listbox_VE->color(FL_BACKGROUND2_COLOR);
        listbox_VE->selection_color(FL_BACKGROUND_COLOR);
        listbox_VE->labeltype(FL_NORMAL_LABEL);
        listbox_VE->labelfont(0);
        listbox_VE->labelsize(14);
        listbox_VE->labelcolor(FL_FOREGROUND_COLOR);
        listbox_VE->callback((Fl_Callback*)cb_listbox_VE);
        listbox_VE->align(Fl_Align(FL_ALIGN_LEFT));
        listbox_VE->when(FL_WHEN_RELEASE);
        o->add(szProsigns);
        o->value(progStatus.VE.c_str()); o->labelsize(FL_NORMAL_SIZE);
        listbox_VE->end();
      } // Fl_ListBox* listbox_VE
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(567, 222, 113, 157);
      o->box(FL_ENGRAVED_FRAME);
      { btn_start_xmt = new Fl_Button(575, 227, 85, 20, gettext("[  TX"));
      } // Fl_Button* btn_start_xmt
      { btn_end_xmt = new Fl_Button(575, 258, 85, 20, gettext("]  RX"));
      } // Fl_Button* btn_end_xmt
      { btn_append_call = new Fl_Button(575, 290, 85, 20, gettext("~C  CALL"));
      } // Fl_Button* btn_append_call
      { btn_append_name = new Fl_Button(575, 322, 85, 20, gettext("~N NAME"));
      } // Fl_Button* btn_append_name
      { btn_append_rst = new Fl_Button(575, 354, 85, 20, gettext("~R RSTout"));
      } // Fl_Button* btn_append_rst
      o->end();
    } // Fl_Group* o
    { btn_cancel_edit = new Fl_Button(10, 352, 65, 22, gettext("Cancel"));
      btn_cancel_edit->tooltip(gettext("Exit editor, discard changes"));
      btn_cancel_edit->callback((Fl_Callback*)cb_btn_cancel_edit);
    } // Fl_Button* btn_cancel_edit
    { btn_apply_edit = new Fl_Button(84, 352, 65, 22, gettext("Apply"));
      btn_apply_edit->tooltip(gettext("Apply current changes to function keys"));
      btn_apply_edit->callback((Fl_Callback*)cb_btn_apply_edit);
    } // Fl_Button* btn_apply_edit
    { btn_done_edit = new Fl_Button(158, 352, 65, 22, gettext("Close"));
      btn_done_edit->tooltip(gettext("Apply changes and close editor"));
      btn_done_edit->callback((Fl_Callback*)cb_btn_done_edit);
    } // Fl_Button* btn_done_edit
    { Fl_Group* o = new Fl_Group(24, 24, 15, 15);
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(279, 350, 282, 29);
      o->box(FL_ENGRAVED_BOX);
      { btn_append_contest_nbr = new Fl_Button(286, 354, 85, 20, gettext("~# Cntst #"));
      } // Fl_Button* btn_append_contest_nbr
      { btn_append_decr = new Fl_Button(376, 354, 85, 20, gettext("~- Decr\'"));
      } // Fl_Button* btn_append_decr
      { btn_append_incr = new Fl_Button(466, 354, 85, 20, gettext("~+ Incr\'"));
      } // Fl_Button* btn_append_incr
      o->end();
    } // Fl_Group* o
    o->resizable(o);
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_ComboBox *select_cwioPORT=(Fl_ComboBox *)0;

static void cb_select_cwioPORT(Fl_ComboBox* o, void*) {
  progStatus.cwioPORT = o->value();
}

Fl_Light_Button *btn_cwioCONNECT=(Fl_Light_Button *)0;

static void cb_btn_cwioCONNECT(Fl_Light_Button* o, void*) {
  if (o->value() == 0) {
    close_cwkey();
    btn_cwioCAT->activate();
    btn_cwioAUX->activate();
    btn_cwioSEP->activate();
    progStatus.cwioCONNECTED = 0;
  }
  else if (!open_cwkey()) {
    o->value(0);
    btn_cwioCAT->activate();
    btn_cwioAUX->activate();
    btn_cwioSEP->activate();
    progStatus.cwioCONNECTED = 0;
  } else {
    btn_cwioCAT->value(0); btn_cwioCAT->deactivate();
    btn_cwioAUX->value(0); btn_cwioAUX->deactivate();
    btn_cwioSEP->value(0); btn_cwioSEP->deactivate();
    progStatus.cwioCONNECTED = 1;
  }
  progStatus.cwioSHARED = 0;
}

Fl_Check_Button *btn_cwioCAT=(Fl_Check_Button *)0;

static void cb_btn_cwioCAT(Fl_Check_Button* o, void*) {
  if (o->value()) {
    progStatus.cwioSHARED = 1;
    btn_cwioAUX->value(0); btn_cwioAUX->deactivate();
    btn_cwioSEP->value(0); btn_cwioSEP->deactivate();
    btn_cwioCONNECT->value(0); btn_cwioCONNECT->deactivate();
    select_cwioPORT->value("NONE"); select_cwioPORT->deactivate();
  }else {
    progStatus.cwioSHARED = 0;
    btn_cwioCONNECT->activate();
    btn_cwioAUX->activate();
    btn_cwioSEP->activate();
    select_cwioPORT->activate();
  }
}

Fl_Check_Button *btn_cwioAUX=(Fl_Check_Button *)0;

static void cb_btn_cwioAUX(Fl_Check_Button* o, void*) {
  if (o->value()) {
    progStatus.cwioSHARED = 2;
    btn_cwioCAT->value(0); btn_cwioCAT->deactivate();
    btn_cwioSEP->value(0); btn_cwioSEP->deactivate();
    btn_cwioCONNECT->value(0); btn_cwioCONNECT->deactivate();
    select_cwioPORT->value("NONE"); select_cwioPORT->deactivate();
  }else {
    progStatus.cwioSHARED = 0;
    btn_cwioCONNECT->activate();
    btn_cwioCAT->activate();
    btn_cwioSEP->activate();
    select_cwioPORT->activate();
  }
}

Fl_Check_Button *btn_cwioSEP=(Fl_Check_Button *)0;

static void cb_btn_cwioSEP(Fl_Check_Button* o, void*) {
  if (o->value()) {
    progStatus.cwioSHARED = 3;
    btn_cwioAUX->value(0); btn_cwioAUX->deactivate();
    btn_cwioCAT->value(0); btn_cwioCAT->deactivate();
    btn_cwioCONNECT->value(0); btn_cwioCONNECT->deactivate();
    select_cwioPORT->value("NONE"); select_cwioPORT->deactivate();
  }else {
    progStatus.cwioSHARED = 0;
    btn_cwioCONNECT->activate();
    btn_cwioAUX->activate();
    btn_cwioCAT->activate();
    select_cwioPORT->activate();
  }
}

Fl_ListBox *listbox_cwioKEYLINE=(Fl_ListBox *)0;

static void cb_listbox_cwioKEYLINE(Fl_ListBox* o, void*) {
  progStatus.cwioKEYLINE = o->index();
}

Fl_Spinner *cntr_cwioPTT=(Fl_Spinner *)0;

static void cb_cntr_cwioPTT(Fl_Spinner* o, void*) {
  progStatus.cwioPTT = o->value();
}

Fl_Light_Button *btn_cw_dtr_calibrate=(Fl_Light_Button *)0;

static void cb_btn_cw_dtr_calibrate(Fl_Light_Button*, void*) {
  calibrate_cwio();
}

Fl_Counter *cnt_cwio_comp=(Fl_Counter *)0;

static void cb_cnt_cwio_comp(Fl_Counter* o, void*) {
  progStatus.cwio_comp = o->value();
}

Fl_Check_Button *btn_cwioINVERTED=(Fl_Check_Button *)0;

static void cb_btn_cwioINVERTED(Fl_Check_Button* o, void*) {
  progStatus.cwioINVERTED = o->value();
  reset_cwioport();
}

Fl_Counter *cnt_cwio_keycorr=(Fl_Counter *)0;

static void cb_cnt_cwio_keycorr(Fl_Counter* o, void*) {
  progStatus.cwio_keycorr = o->value();
}

Fl_Double_Window* new_cwio_config_dialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(670, 100, gettext("CW Configuration"));
    w = o; (void)w;
    { Fl_Group* o = new Fl_Group(1, 0, 668, 98);
      o->box(FL_ENGRAVED_FRAME);
      { Fl_ComboBox* o = select_cwioPORT = new Fl_ComboBox(73, 69, 496, 23, gettext("Ser. Port"));
        select_cwioPORT->tooltip(gettext("CWIO serial port"));
        select_cwioPORT->box(FL_DOWN_BOX);
        select_cwioPORT->color((Fl_Color)53);
        select_cwioPORT->selection_color(FL_BACKGROUND_COLOR);
        select_cwioPORT->labeltype(FL_NORMAL_LABEL);
        select_cwioPORT->labelfont(0);
        select_cwioPORT->labelsize(14);
        select_cwioPORT->labelcolor(FL_FOREGROUND_COLOR);
        select_cwioPORT->callback((Fl_Callback*)cb_select_cwioPORT);
        select_cwioPORT->align(Fl_Align(FL_ALIGN_LEFT));
        select_cwioPORT->when(FL_WHEN_RELEASE);
        o->value(progStatus.cwioPORT.c_str());
        select_cwioPORT->end();
      } // Fl_ComboBox* select_cwioPORT
      { Fl_Light_Button* o = btn_cwioCONNECT = new Fl_Light_Button(578, 69, 80, 23, gettext("Connect"));
        btn_cwioCONNECT->callback((Fl_Callback*)cb_btn_cwioCONNECT);
        o->value(progStatus.cwioCONNECTED);
      } // Fl_Light_Button* btn_cwioCONNECT
      { Fl_Check_Button* o = btn_cwioCAT = new Fl_Check_Button(70, 15, 18, 15, gettext("Use CAT"));
        btn_cwioCAT->tooltip(gettext("Use DTR/RTS on CAT serial port"));
        btn_cwioCAT->down_box(FL_DOWN_BOX);
        btn_cwioCAT->callback((Fl_Callback*)cb_btn_cwioCAT);
        btn_cwioCAT->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.cwioSHARED == 1);
      } // Fl_Check_Button* btn_cwioCAT
      { Fl_Check_Button* o = btn_cwioAUX = new Fl_Check_Button(71, 46, 18, 15, gettext("Use AUX"));
        btn_cwioAUX->tooltip(gettext("Use DTR/RTS on Auxiliary serial port"));
        btn_cwioAUX->down_box(FL_DOWN_BOX);
        btn_cwioAUX->callback((Fl_Callback*)cb_btn_cwioAUX);
        btn_cwioAUX->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.cwioSHARED == 2);
      } // Fl_Check_Button* btn_cwioAUX
      { Fl_Check_Button* o = btn_cwioSEP = new Fl_Check_Button(160, 15, 18, 15, gettext("Use SEP"));
        btn_cwioSEP->tooltip(gettext("Use DTR/RTS Separate serial port"));
        btn_cwioSEP->down_box(FL_DOWN_BOX);
        btn_cwioSEP->callback((Fl_Callback*)cb_btn_cwioSEP);
        btn_cwioSEP->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.cwioSHARED == 3);
      } // Fl_Check_Button* btn_cwioSEP
      { Fl_ListBox* o = listbox_cwioKEYLINE = new Fl_ListBox(593, 41, 65, 24, gettext("Keyline"));
        listbox_cwioKEYLINE->tooltip(gettext("Select either DTR or RTS for keyline"));
        listbox_cwioKEYLINE->box(FL_DOWN_BOX);
        listbox_cwioKEYLINE->color(FL_BACKGROUND2_COLOR);
        listbox_cwioKEYLINE->selection_color(FL_BACKGROUND_COLOR);
        listbox_cwioKEYLINE->labeltype(FL_NORMAL_LABEL);
        listbox_cwioKEYLINE->labelfont(0);
        listbox_cwioKEYLINE->labelsize(14);
        listbox_cwioKEYLINE->labelcolor(FL_FOREGROUND_COLOR);
        listbox_cwioKEYLINE->callback((Fl_Callback*)cb_listbox_cwioKEYLINE);
        listbox_cwioKEYLINE->align(Fl_Align(FL_ALIGN_LEFT));
        listbox_cwioKEYLINE->when(FL_WHEN_RELEASE);
        o->add("None|RTS|DTR");
        o->index(progStatus.cwioKEYLINE);
        listbox_cwioKEYLINE->end();
      } // Fl_ListBox* listbox_cwioKEYLINE
      { Fl_Spinner* o = cntr_cwioPTT = new Fl_Spinner(608, 10, 50, 25, gettext("PTT delay"));
        cntr_cwioPTT->tooltip(gettext("PTT delay before keydown\n0 = Break-in"));
        cntr_cwioPTT->minimum(0);
        cntr_cwioPTT->value(0);
        cntr_cwioPTT->callback((Fl_Callback*)cb_cntr_cwioPTT);
        o->value(progStatus.cwioPTT);
      } // Fl_Spinner* cntr_cwioPTT
      { btn_cw_dtr_calibrate = new Fl_Light_Button(235, 8, 56, 24, gettext("Calib\'"));
        btn_cw_dtr_calibrate->tooltip(gettext("Calibrate WPM timing"));
        btn_cw_dtr_calibrate->selection_color((Fl_Color)6);
        btn_cw_dtr_calibrate->callback((Fl_Callback*)cb_btn_cw_dtr_calibrate);
      } // Fl_Light_Button* btn_cw_dtr_calibrate
      { Fl_Counter* o = cnt_cwio_comp = new Fl_Counter(400, 8, 130, 24, gettext("WPM Comp"));
        cnt_cwio_comp->tooltip(gettext("Timing compensation msec"));
        cnt_cwio_comp->minimum(-5);
        cnt_cwio_comp->maximum(5);
        cnt_cwio_comp->step(0.001);
        cnt_cwio_comp->callback((Fl_Callback*)cb_cnt_cwio_comp);
        cnt_cwio_comp->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.cwio_comp);
        o->lstep(0.1);
      } // Fl_Counter* cnt_cwio_comp
      { Fl_Check_Button* o = btn_cwioINVERTED = new Fl_Check_Button(160, 46, 18, 15, gettext("Inverted"));
        btn_cwioINVERTED->tooltip(gettext("DTR/RTS signaling is inverted\n(-) keying"));
        btn_cwioINVERTED->down_box(FL_DOWN_BOX);
        btn_cwioINVERTED->callback((Fl_Callback*)cb_btn_cwioINVERTED);
        btn_cwioINVERTED->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.cwioINVERTED);
      } // Fl_Check_Button* btn_cwioINVERTED
      { Fl_Counter* o = cnt_cwio_keycorr = new Fl_Counter(400, 41, 130, 24, gettext("Xcvr Comp"));
        cnt_cwio_keycorr->tooltip(gettext("Compensate for xcv delays (msec)"));
        cnt_cwio_keycorr->minimum(-10);
        cnt_cwio_keycorr->maximum(10);
        cnt_cwio_keycorr->step(0.01);
        cnt_cwio_keycorr->callback((Fl_Callback*)cb_cnt_cwio_keycorr);
        cnt_cwio_keycorr->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.cwio_keycorr);
        o->lstep(0.10);
      } // Fl_Counter* cnt_cwio_keycorr
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Menu_Bar *CWlog_menubar=(Fl_Menu_Bar *)0;

static void cb_cwlog_menu_open(Fl_Menu_*, void*) {
  cwlog_open();
}

static void cb_cwlog_menu_new(Fl_Menu_*, void*) {
  cwlog_new();
}

static void cb_cwlog_menu_save(Fl_Menu_*, void*) {
  cwlog_save();
}

static void cb_cwlog_menu_save_as(Fl_Menu_*, void*) {
  cwlog_save_as();
}

static void cb_cwlog_menu_export_adif(Fl_Menu_*, void*) {
  cwlog_export_adif();
}

static void cb_cwlog_menu_import_adif(Fl_Menu_*, void*) {
  cwlog_import_adif();
}

static void cb_cwlog_menu_dupcheck(Fl_Menu_* o, void*) {
  //cwlog.dupcheck = o->value();
}

static void cb_cwlog_menu_leading_zeros(Fl_Menu_* o, void*) {
  //cwlog.dupcheck = o->value();
}

static void cb_cwlog_menu_cut_numbers(Fl_Menu_* o, void*) {
  //cwlog.cut_nbrs = o->value();
}

Fl_Menu_Item menu_CWlog_menubar[] = {
 {gettext_noop("Files"), 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Open"), 0,  (Fl_Callback*)cb_cwlog_menu_open, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("New"), 0,  (Fl_Callback*)cb_cwlog_menu_new, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Save"), 0,  (Fl_Callback*)cb_cwlog_menu_save, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Save As"), 0,  (Fl_Callback*)cb_cwlog_menu_save_as, 0, 128, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Export ADIF"), 0,  (Fl_Callback*)cb_cwlog_menu_export_adif, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Import ADIF"), 0,  (Fl_Callback*)cb_cwlog_menu_import_adif, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {gettext_noop("Config"), 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Dup check"), 0,  (Fl_Callback*)cb_cwlog_menu_dupcheck, 0, 2, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Leading zeros"), 0,  (Fl_Callback*)cb_cwlog_menu_leading_zeros, 0, 2, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {gettext_noop("Cut numbers"), 0,  (Fl_Callback*)cb_cwlog_menu_cut_numbers, 0, 2, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Output *txt_cwlog_file=(Fl_Output *)0;

static void cb_txt_cwlog_file(Fl_Output* o, void*) {
  //progStatus.cwlogfile_name = o->value();
}

Fl_Group *cw_grp_qso_data=(Fl_Group *)0;

Fl_Input2 *cw_freq=(Fl_Input2 *)0;

Fl_Button *btn_cwlog_clear_qso=(Fl_Button *)0;

static void cb_btn_cwlog_clear_qso(Fl_Button*, void*) {
  cwlog_clear_qso();
}

Fl_Button *btn_cwlog_save_qso=(Fl_Button *)0;

static void cb_btn_cwlog_save_qso(Fl_Button*, void*) {
  cwlog_save_qso();
}

Fl_Button *btn_cwlog_edit_entry=(Fl_Button *)0;

static void cb_btn_cwlog_edit_entry(Fl_Button*, void*) {
  cwlog_edit_entry();
}

Fl_Button *btn_cwlog_delete_entry=(Fl_Button *)0;

static void cb_btn_cwlog_delete_entry(Fl_Button*, void*) {
  cwlog_delete_entry();
}

Fl_Input2 *cw_qso_date=(Fl_Input2 *)0;

Fl_Input2 *cw_qso_time=(Fl_Input2 *)0;

Fl_Input2 *cw_rst_out=(Fl_Input2 *)0;

Fl_Input2 *cw_rst_in=(Fl_Input2 *)0;

Fl_Input2 *cw_xchg_in=(Fl_Input2 *)0;

Fl_Counter *cw_log_nbr=(Fl_Counter *)0;

static void cb_cw_log_nbr(Fl_Counter* o, void*) {
  progStatus.cw_log_nbr = o->value();
}

Fl_Input2 *cw_op_name=(Fl_Input2 *)0;

Fl_Input2 *cw_op_call=(Fl_Input2 *)0;

Fl_Button *btn_cw_datetime=(Fl_Button *)0;

static void cb_btn_cw_datetime(Fl_Button*, void*) {
  cwlog_sort_by_datetime();
}

Fl_Button *btn_cw_time=(Fl_Button *)0;

static void cb_btn_cw_time(Fl_Button*, void*) {
  cwlog_sort_by_datetime();
}

Fl_Button *btn_cw_freq=(Fl_Button *)0;

static void cb_btn_cw_freq(Fl_Button*, void*) {
  cwlog_sort_by_freq();
}

Fl_Button *btn_cw_call=(Fl_Button *)0;

static void cb_btn_cw_call(Fl_Button*, void*) {
  cwlog_sort_by_call();
}

Fl_Button *btn_cw_name=(Fl_Button *)0;

Fl_Button *btn_cw_in=(Fl_Button *)0;

Fl_Button *btn_cw_out=(Fl_Button *)0;

Fl_Button *btn_cw_sent_nbr=(Fl_Button *)0;

static void cb_btn_cw_sent_nbr(Fl_Button*, void*) {
  cwlog_sort_by_nbr();
}

Fl_Button *btn_cw_xchg=(Fl_Button *)0;

Fl_Browser *brwsr_cwlog_entries=(Fl_Browser *)0;

static void cb_brwsr_cwlog_entries(Fl_Browser*, void*) {
  if (!cwlog_editing) cwlog_edit_entry();
}

Fl_Double_Window* new_cwlogbook_dialog() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(670, 280, gettext("Flrig CW Log"));
    w = o; (void)w;
    { CWlog_menubar = new Fl_Menu_Bar(0, 0, 670, 20);
      { Fl_Menu_Item* o = &menu_CWlog_menubar[0];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_CWlog_menubar[1];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_CWlog_menubar[2];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_CWlog_menubar[3];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_CWlog_menubar[4];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_CWlog_menubar[5];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_CWlog_menubar[6];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_CWlog_menubar[8];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_CWlog_menubar[9];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_CWlog_menubar[10];
        o->label(gettext(o->label()));
      }
      { Fl_Menu_Item* o = &menu_CWlog_menubar[11];
        o->label(gettext(o->label()));
      }
      CWlog_menubar->menu(menu_CWlog_menubar);
    } // Fl_Menu_Bar* CWlog_menubar
    { Fl_Group* o = new Fl_Group(2, 22, 668, 29);
      o->box(FL_ENGRAVED_FRAME);
      { txt_cwlog_file = new Fl_Output(75, 26, 590, 22, gettext("Log File:"));
        txt_cwlog_file->callback((Fl_Callback*)cb_txt_cwlog_file);
        //->value(progStatus.cwlogfile_name);
      } // Fl_Output* txt_cwlog_file
      o->end();
    } // Fl_Group* o
    { cw_grp_qso_data = new Fl_Group(2, 52, 560, 30);
      cw_grp_qso_data->box(FL_ENGRAVED_BOX);
      { cw_freq = new Fl_Input2(43, 56, 120, 22, gettext("Freq"));
        cw_freq->tooltip(gettext("Frequency"));
        cw_freq->box(FL_DOWN_BOX);
        cw_freq->color(FL_BACKGROUND2_COLOR);
        cw_freq->selection_color(FL_SELECTION_COLOR);
        cw_freq->labeltype(FL_NORMAL_LABEL);
        cw_freq->labelfont(0);
        cw_freq->labelsize(14);
        cw_freq->labelcolor(FL_FOREGROUND_COLOR);
        cw_freq->align(Fl_Align(FL_ALIGN_LEFT));
        cw_freq->when(FL_WHEN_RELEASE);
      } // Fl_Input2* cw_freq
      { btn_cwlog_clear_qso = new Fl_Button(380, 56, 60, 22, gettext("Clear"));
        btn_cwlog_clear_qso->tooltip(gettext("Clear cwlog entries"));
        btn_cwlog_clear_qso->callback((Fl_Callback*)cb_btn_cwlog_clear_qso);
      } // Fl_Button* btn_cwlog_clear_qso
      { btn_cwlog_save_qso = new Fl_Button(440, 56, 60, 22, gettext("Save"));
        btn_cwlog_save_qso->tooltip(gettext("Save QSO data to cwlog file"));
        btn_cwlog_save_qso->callback((Fl_Callback*)cb_btn_cwlog_save_qso);
      } // Fl_Button* btn_cwlog_save_qso
      { btn_cwlog_edit_entry = new Fl_Button(501, 56, 60, 22, gettext("Edit"));
        btn_cwlog_edit_entry->tooltip(gettext("Delete Entry"));
        btn_cwlog_edit_entry->callback((Fl_Callback*)cb_btn_cwlog_edit_entry);
      } // Fl_Button* btn_cwlog_edit_entry
      { btn_cwlog_delete_entry = new Fl_Button(492, 56, 60, 22, gettext("Delete"));
        btn_cwlog_delete_entry->tooltip(gettext("Delete Entry"));
        btn_cwlog_delete_entry->callback((Fl_Callback*)cb_btn_cwlog_delete_entry);
        btn_cwlog_delete_entry->hide();
      } // Fl_Button* btn_cwlog_delete_entry
      { cw_qso_date = new Fl_Input2(193, 56, 85, 22, gettext("Dt"));
        cw_qso_date->tooltip(gettext("QSO call\nQuery flcwlog if connected"));
        cw_qso_date->box(FL_DOWN_BOX);
        cw_qso_date->color(FL_BACKGROUND2_COLOR);
        cw_qso_date->selection_color(FL_SELECTION_COLOR);
        cw_qso_date->labeltype(FL_NORMAL_LABEL);
        cw_qso_date->labelfont(0);
        cw_qso_date->labelsize(14);
        cw_qso_date->labelcolor(FL_FOREGROUND_COLOR);
        cw_qso_date->align(Fl_Align(FL_ALIGN_LEFT));
        cw_qso_date->when(FL_WHEN_RELEASE);
      } // Fl_Input2* cw_qso_date
      { cw_qso_time = new Fl_Input2(313, 56, 55, 22, gettext("Tm:"));
        cw_qso_time->box(FL_DOWN_BOX);
        cw_qso_time->color(FL_BACKGROUND2_COLOR);
        cw_qso_time->selection_color(FL_SELECTION_COLOR);
        cw_qso_time->labeltype(FL_NORMAL_LABEL);
        cw_qso_time->labelfont(0);
        cw_qso_time->labelsize(14);
        cw_qso_time->labelcolor(FL_FOREGROUND_COLOR);
        cw_qso_time->align(Fl_Align(FL_ALIGN_LEFT));
        cw_qso_time->when(FL_WHEN_RELEASE);
      } // Fl_Input2* cw_qso_time
      cw_grp_qso_data->end();
    } // Fl_Group* cw_grp_qso_data
    { Fl_Group* o = new Fl_Group(565, 52, 103, 62);
      o->box(FL_ENGRAVED_BOX);
      { cw_rst_out = new Fl_Input2(622, 56, 40, 22, gettext("RSTout"));
        cw_rst_out->tooltip(gettext("Send RST"));
        cw_rst_out->box(FL_DOWN_BOX);
        cw_rst_out->color(FL_BACKGROUND2_COLOR);
        cw_rst_out->selection_color(FL_SELECTION_COLOR);
        cw_rst_out->labeltype(FL_NORMAL_LABEL);
        cw_rst_out->labelfont(0);
        cw_rst_out->labelsize(14);
        cw_rst_out->labelcolor(FL_FOREGROUND_COLOR);
        cw_rst_out->align(Fl_Align(FL_ALIGN_LEFT));
        cw_rst_out->when(FL_WHEN_RELEASE);
      } // Fl_Input2* cw_rst_out
      { cw_rst_in = new Fl_Input2(624, 87, 40, 22, gettext("RST in"));
        cw_rst_in->tooltip(gettext("Send RST"));
        cw_rst_in->box(FL_DOWN_BOX);
        cw_rst_in->color(FL_BACKGROUND2_COLOR);
        cw_rst_in->selection_color(FL_SELECTION_COLOR);
        cw_rst_in->labeltype(FL_NORMAL_LABEL);
        cw_rst_in->labelfont(0);
        cw_rst_in->labelsize(14);
        cw_rst_in->labelcolor(FL_FOREGROUND_COLOR);
        cw_rst_in->align(Fl_Align(FL_ALIGN_LEFT));
        cw_rst_in->when(FL_WHEN_RELEASE);
      } // Fl_Input2* cw_rst_in
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(2, 84, 560, 30);
      o->box(FL_ENGRAVED_FRAME);
      { cw_xchg_in = new Fl_Input2(313, 87, 150, 22, gettext("Xch"));
        cw_xchg_in->tooltip(gettext("Input exchange"));
        cw_xchg_in->box(FL_DOWN_BOX);
        cw_xchg_in->color(FL_BACKGROUND2_COLOR);
        cw_xchg_in->selection_color(FL_SELECTION_COLOR);
        cw_xchg_in->labeltype(FL_NORMAL_LABEL);
        cw_xchg_in->labelfont(0);
        cw_xchg_in->labelsize(14);
        cw_xchg_in->labelcolor(FL_FOREGROUND_COLOR);
        cw_xchg_in->align(Fl_Align(FL_ALIGN_LEFT));
        cw_xchg_in->when(FL_WHEN_RELEASE);
      } // Fl_Input2* cw_xchg_in
      { Fl_Counter* o = cw_log_nbr = new Fl_Counter(491, 87, 70, 22, gettext("#:"));
        cw_log_nbr->tooltip(gettext("QSO number (out)"));
        cw_log_nbr->type(1);
        cw_log_nbr->step(1);
        cw_log_nbr->callback((Fl_Callback*)cb_cw_log_nbr);
        cw_log_nbr->align(Fl_Align(FL_ALIGN_LEFT));
        o->value(progStatus.cw_log_nbr);
      } // Fl_Counter* cw_log_nbr
      { cw_op_name = new Fl_Input2(193, 88, 85, 22, gettext("Nm"));
        cw_op_name->box(FL_DOWN_BOX);
        cw_op_name->color(FL_BACKGROUND2_COLOR);
        cw_op_name->selection_color(FL_SELECTION_COLOR);
        cw_op_name->labeltype(FL_NORMAL_LABEL);
        cw_op_name->labelfont(0);
        cw_op_name->labelsize(14);
        cw_op_name->labelcolor(FL_FOREGROUND_COLOR);
        cw_op_name->align(Fl_Align(FL_ALIGN_LEFT));
        cw_op_name->when(FL_WHEN_RELEASE);
      } // Fl_Input2* cw_op_name
      { cw_op_call = new Fl_Input2(43, 88, 120, 22, gettext("Call"));
        cw_op_call->tooltip(gettext("QSO call\nQuery flcwlog if connected"));
        cw_op_call->box(FL_DOWN_BOX);
        cw_op_call->color(FL_BACKGROUND2_COLOR);
        cw_op_call->selection_color(FL_SELECTION_COLOR);
        cw_op_call->labeltype(FL_NORMAL_LABEL);
        cw_op_call->labelfont(0);
        cw_op_call->labelsize(14);
        cw_op_call->labelcolor(FL_FOREGROUND_COLOR);
        cw_op_call->align(Fl_Align(FL_ALIGN_LEFT));
        cw_op_call->when(FL_WHEN_RELEASE);
      } // Fl_Input2* cw_op_call
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(2, 113, 674, 170);
      { Fl_Group* o = new Fl_Group(2, 116, 668, 22);
        { btn_cw_datetime = new Fl_Button(2, 116, 80, 22, gettext("Date"));
          btn_cw_datetime->box(FL_BORDER_BOX);
          btn_cw_datetime->color((Fl_Color)51);
          btn_cw_datetime->callback((Fl_Callback*)cb_btn_cw_datetime);
        } // Fl_Button* btn_cw_datetime
        { btn_cw_time = new Fl_Button(81, 116, 45, 22, gettext("Time"));
          btn_cw_time->box(FL_BORDER_BOX);
          btn_cw_time->color((Fl_Color)51);
          btn_cw_time->callback((Fl_Callback*)cb_btn_cw_time);
        } // Fl_Button* btn_cw_time
        { btn_cw_freq = new Fl_Button(126, 116, 70, 22, gettext("Freq"));
          btn_cw_freq->box(FL_BORDER_BOX);
          btn_cw_freq->color((Fl_Color)51);
          btn_cw_freq->callback((Fl_Callback*)cb_btn_cw_freq);
        } // Fl_Button* btn_cw_freq
        { btn_cw_call = new Fl_Button(196, 116, 75, 22, gettext("Call"));
          btn_cw_call->box(FL_BORDER_BOX);
          btn_cw_call->color((Fl_Color)51);
          btn_cw_call->callback((Fl_Callback*)cb_btn_cw_call);
        } // Fl_Button* btn_cw_call
        { btn_cw_name = new Fl_Button(271, 116, 75, 22, gettext("Name"));
          btn_cw_name->box(FL_BORDER_BOX);
          btn_cw_name->color((Fl_Color)51);
        } // Fl_Button* btn_cw_name
        { btn_cw_in = new Fl_Button(346, 116, 40, 22, gettext("In"));
          btn_cw_in->box(FL_BORDER_BOX);
          btn_cw_in->color((Fl_Color)51);
        } // Fl_Button* btn_cw_in
        { btn_cw_out = new Fl_Button(386, 116, 40, 22, gettext("Out"));
          btn_cw_out->box(FL_BORDER_BOX);
          btn_cw_out->color((Fl_Color)51);
        } // Fl_Button* btn_cw_out
        { btn_cw_sent_nbr = new Fl_Button(426, 116, 55, 22, gettext("Nbr"));
          btn_cw_sent_nbr->box(FL_BORDER_BOX);
          btn_cw_sent_nbr->color((Fl_Color)51);
          btn_cw_sent_nbr->callback((Fl_Callback*)cb_btn_cw_sent_nbr);
        } // Fl_Button* btn_cw_sent_nbr
        { btn_cw_xchg = new Fl_Button(481, 116, 185, 22, gettext("Exchange"));
          btn_cw_xchg->box(FL_BORDER_BOX);
          btn_cw_xchg->color((Fl_Color)51);
          Fl_Group::current()->resizable(btn_cw_xchg);
        } // Fl_Button* btn_cw_xchg
        o->end();
      } // Fl_Group* o
      { Fl_Browser* o = brwsr_cwlog_entries = new Fl_Browser(2, 140, 666, 141);
        brwsr_cwlog_entries->type(2);
        brwsr_cwlog_entries->selection_color((Fl_Color)230);
        brwsr_cwlog_entries->callback((Fl_Callback*)cb_brwsr_cwlog_entries);
        Fl_Group::current()->resizable(brwsr_cwlog_entries);
        static int widths[]={80,45,70,75,75,40,40,55,0};
        o->column_widths(widths);
        o->column_char('\t');
        o->has_scrollbar(Fl_Browser_::VERTICAL_ALWAYS);
      } // Fl_Browser* brwsr_cwlog_entries
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
